"""P4 -- `Config`, the object composing every namelist group.

    model.config.ocean_epbl.mstar = 1.2
    model.config.ocean_bt.split_scheme = "pred_corr"   # enum, validated on assign
    print(model.config.to_namelist())                # exactly what will be sent

612 knobs across 57 groups, reachable and typed, ALL from the live
`nml_schema_t` (`_config_generated.py`, regenerated by
`tools/gen_python_config.py` -- never hand-edited). `&ocean_bc_nml` (53
knobs) joined the schema in P4.5 -- there is no more hand-written stub.

ABSENCE IS THE DEFAULT (D2.0 rule 2): a freshly constructed `Config` has
every knob unset, and `to_namelist()` emits ONLY explicitly-assigned
knobs. This is what gives bit-identity to existing namelists and tests --
`read_config_from_string` on an empty buffer keeps the pristine
`config_t` defaults (`rdb_config.F90:2734`'s own docstring).

This layer deliberately does NOT re-implement `validate_config`'s
cross-knob rules or the schema's per-group `cross_check` callbacks
(`rdb_nml_schema.F90:174`) -- see `_knob.py`'s module docstring. Those
stay in Fortran and surface as `ConfigValidationError`/`ConfigParseError`
through the error ring once the composed namelist reaches
`read_config_from_string` (i.e. once a `Config` is handed to `Model`).
"""

from __future__ import annotations

from ._config_generated import GENERATED_GROUPS

#: schema group name -> Group subclass, in the order build_rdb_schema
#: registers them. Every group is generated now (P4.5 closed the last
#: hand-written stub, ocean_bc).
ALL_GROUPS = dict(GENERATED_GROUPS)

N_GROUPS = len(ALL_GROUPS)
N_KNOBS = sum(
    len([n for n in vars(cls) if not n.startswith("_")
         and hasattr(getattr(cls, n), "kind")])
    for cls in ALL_GROUPS.values()
)


class _ConfigMeta(type):
    """Puts every group CLASS (not an instance) on `Config` itself, so
    `Config.ocean_epbl.mstar.default` works without constructing a
    `Config` -- the descriptor's `__get__(obj=None, ...)` returns itself
    when accessed through the class."""

    def __new__(mcls, name, bases, ns):
        for attr, cls in ALL_GROUPS.items():
            ns[attr] = cls
        return super().__new__(mcls, name, bases, ns)


class Config(metaclass=_ConfigMeta):
    """Every namelist group, as an attribute.

    ``Config()`` builds one fresh (all-unset) instance of every group.
    Every generated-layer knob starts as the ``MISSING`` sentinel; only
    knobs you assign are serialised by :meth:`to_namelist`.
    """

    def __init__(self):
        for attr, cls in ALL_GROUPS.items():
            setattr(self, attr, cls())

    def to_namelist(self) -> str:
        """Serialise every explicitly-set knob to one namelist string.

        That string is the ONLY thing that crosses the ABI
        (``rdb_ocean_create_from_string``,
        ``include/rdb_ocean.h``) -- it goes through
        ``read_config_from_string`` and therefore the identical strict
        schema parse, the identical ``cross_check`` callbacks, the
        identical post-parse cascades, and the identical
        ``validate_config`` as a namelist file on disk. A ``Config`` with
        nothing assigned serialises to the empty string, which
        ``read_config_from_string`` treats as "keep pristine defaults".
        """
        parts = []
        for attr, cls in ALL_GROUPS.items():
            inst = getattr(self, attr)
            lines = inst._namelist_lines()
            if lines:
                parts.append("&" + cls._nml_name + "_nml\n" +
                              "\n".join(lines) + "\n/")
        if not parts:
            return ""
        # Trailing newline after the final group's closing `/` -- matches
        # every namelist this package ships (the test fixtures, every
        # .nml in validation_examples/), which already end in "/\n".
        # Historically load-bearing for the hand-rolled &ocean_bc_nml
        # internal-file reader (an unterminated last group failed with
        # "end of file reached without finding group"); that reader is
        # gone (P4.5 migrated the group onto the strict schema), but the
        # trailing newline is harmless and kept for consistency.
        return "\n".join(parts) + "\n"

    def explicit_knobs(self):
        """Yield ``(group, key, value)`` for every knob explicitly set on
        this config -- the live equivalent of MOM6's
        ``parameter_doc.short`` (which Roundabout already writes at
        ``app/main.F90:87-88`` via ``schema%write_doc_short``)."""
        for attr, cls in ALL_GROUPS.items():
            inst = getattr(self, attr)
            for name in inst._explicit_names():
                desc = getattr(cls, name)
                yield (cls._nml_name, name, inst.__dict__[desc._attr])

    def write_namelist(self, path):
        """Write :meth:`to_namelist`'s text to `path`."""
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.to_namelist())

    def __repr__(self):
        n = sum(1 for _ in self.explicit_knobs())
        return f"Config({n} knob(s) set)"
