!! Unit tests for `eos_freezing_point` (`rdb_eos`) — the
!! ocean-side sea-ice prerequisite (PLAN_SEA_ICE.md, PR 1), and for the
!! `&ocean_eos_nml tfreeze_set` liquidus coefficient SETS.
!!
!! The form is linear for every EOS variant:
!!   T_f = λ1·S + λ2 + λ3·p
!! with the triple carried on the EOS handle (`eos%tfr_s`/`tfr_0`/`tfr_p`)
!! and chosen by name:
!!   * `"seaice"` (DEFAULT) — SIS2/MOM6, λ = (−0.054, 0, −7.53e-8).
!!   * `"isomip"` — ISOMIP+ / Asay-Davis et al. (2016) GMD 9, Table 4
!!     p. 2483, consumed in their eq. (25) p. 2485:
!!     λ = (−0.0573, 0.0832, −7.53e-8).
!!
!! Cases:
!!   * Reference point — T_f(S=35, p=0) = −1.89 °C exactly.
!!   * Fresh water — T_f(0, 0) = 0.
!!   * Monotonic decreasing in S over [0, 40].
!!   * Pressure depression — T_f(S, p>0) < T_f(S, 0) by TFR_P_COEFF·p.
!!   * Elemental broadcast — one call over a salinity ARRAY matches the
!!     scalar loop element-by-element.
!!   * Variant-invariant — linear / Wright / Roquet handles all return
!!     the same liquidus (the SET, not the density variant, selects it).
!!   * BIT-IDENTITY of the default set against the pre-knob literal
!!     expression, over a sweep including S=0 and p=0, compared through
!!     the raw bit pattern (see `test_default_set_bit_identical`).
!!   * ISOMIP+ hand values, and agreement with the Python prototype
!!     oracle (`ice_shelf_melt/oracle.json`).
!!   * The set-to-set difference, in closed form.
!!   * Knob parsing — round-trip, fail-loud typo, and the fail-loud path
!!     through `validate_config`.
!!   * End-to-end: the configured set reaches the handle the SEA-ICE
!!     kernels are actually handed, through the production configure
!!     path.
module test_ocean_freezing_point
   use, intrinsic :: iso_fortran_env, only: int64
   use testdrive, only: new_unittest, unittest_type, error_type, check
   use rdb_constants, only: wp
   use rdb_config, only: config_t, validate_config
   use rdb_grid, only: hgrid_t
   use rdb_ocean_state, only: ocean_state_t
   use rdb_ocean_setup, only: configure_ocean_drag
   use rdb_ocean_status, only: OCEAN_STATUS_OK, OCEAN_STATUS_ERR_CONFIG_VALIDATE
   use rdb_eos, only: eos_t, eos_freezing_point, &
                      TFR_S_COEFF, TFR_0_COEFF, TFR_P_COEFF, &
                      TFR_ISOMIP_S_COEFF, TFR_ISOMIP_0_COEFF, TFR_ISOMIP_P_COEFF, &
                      parse_tfreeze_set, eos_apply_tfreeze_set, &
                      TFREEZE_SET_SEAICE, TFREEZE_SET_ISOMIP, TFREEZE_SET_INVALID, &
                      EOS_VARIANT_LINEAR, EOS_VARIANT_WRIGHT_97, &
                      EOS_VARIANT_ROQUET_SPV
   implicit none
   private

   public :: collect_ocean_freezing_point_tests

   ! ------------------------------------------------------------------
   ! Golden numbers for the ISOMIP+ set.
   !
   ! Hand values (λ1·S + λ2 + λ3·p with λ = (−0.0573, 0.0832, −7.53e-8)):
   !   S = 34.5, p = 0      -> −0.0573*34.5 + 0.0832            = −1.89365
   !   S = 34.5, p = 5.0e6  -> −1.89365 + (−7.53e-8*5.0e6)      = −2.27015
   !
   ! Prototype-oracle cross-check.  Source:
   !   /home/jorge/nci/cdx/python_prototypes/ice_shelf_melt/oracle.json
   !   (schema "ice_shelf_melt/oracle/v1", generated by make_oracle.py at
   !    prototype git commit 38cbe556772edb96a7b55fb4756329d9aed7eed7).
   ! Each case's `outputs.T_freeze_far` is `tfreeze(S_w, p_b)` evaluated
   ! with the named liquidus; the three cases below all carry
   ! `inputs.liquidus == "isomip"`.  House convention: golden numbers
   ! cite their prototype source.
   !
   !   liq_isomip__mild_deep_mid       S_w = 34.5, p_b = 4.5e6 -> −2.2325
   !   jenkins10_native__mild_deep_mid S_w = 34.5, p_b = 4.5e6 -> −2.2325
   !   liq_isomip__cold_deep_slow      S_w = 34.3, p_b = 8.1e6 -> −2.49212
   ! ------------------------------------------------------------------
   real(wp), parameter :: ISOMIP_TF_S345_P0 = -1.89365_wp
   real(wp), parameter :: ISOMIP_TF_S345_P5E6 = -2.27015_wp

   real(wp), parameter :: ORACLE_S(3) = [34.5_wp, 34.5_wp, 34.3_wp]
   real(wp), parameter :: ORACLE_P(3) = [4.5e6_wp, 4.5e6_wp, 8.1e6_wp]
   real(wp), parameter :: ORACLE_TF(3) = [-2.2325_wp, -2.2325_wp, -2.49212_wp]
   real(wp), parameter :: ORACLE_TOL = 1.0e-13_wp

contains

   subroutine collect_ocean_freezing_point_tests(testsuite)
      type(unittest_type), allocatable, intent(out) :: testsuite(:)

      testsuite = [ &
                  new_unittest("freezing_point_reference_s35", test_reference_s35), &
                  new_unittest("freezing_point_fresh_water_zero", test_fresh_zero), &
                  new_unittest("freezing_point_monotonic_in_s", test_monotonic_s), &
                  new_unittest("freezing_point_pressure_depression", test_pressure), &
                  new_unittest("freezing_point_elemental_array", test_elemental_array), &
                  new_unittest("freezing_point_variant_invariant_v1", test_variants), &
                  new_unittest("freezing_point_default_set_bit_identical", &
                               test_default_set_bit_identical), &
                  new_unittest("freezing_point_isomip_hand_values", test_isomip_hand_values), &
                  new_unittest("freezing_point_isomip_matches_oracle", test_isomip_oracle), &
                  new_unittest("freezing_point_set_difference", test_set_difference), &
                  new_unittest("freezing_point_tfreeze_set_parse", test_tfreeze_set_parse), &
                  new_unittest("freezing_point_tfreeze_set_fail_loud", &
                               test_tfreeze_set_fail_loud), &
                  new_unittest("freezing_point_configured_set_reaches_ice_handle", &
                               test_configured_set_reaches_ice_handle) &
                  ]
   end subroutine collect_ocean_freezing_point_tests

   subroutine make_eos(eos)
      !! Minimal EOS handle — the point function only reads the flat POD,
      !! so a default-init handle (linear variant) suffices.
      type(eos_t), intent(out) :: eos
      type(hgrid_t) :: grid
      call grid%init(4, 4, 2, 1.0_wp, 1.0_wp)
      call eos%init(grid)
   end subroutine make_eos

   subroutine test_reference_s35(error)
      !! SIS2 reference point: T_f(35 PSU, surface) = −0.054·35 = −1.89 °C.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_f

      call make_eos(eos)
      t_f = eos_freezing_point(eos, 35.0_wp, 0.0_wp)
      call check(error, abs(t_f - (-1.89_wp)) < 1.0e-12_wp, &
                 "T_f(S=35, p=0) must be -1.89 degC")
      call eos%destroy()
   end subroutine test_reference_s35

   subroutine test_fresh_zero(error)
      !! Fresh water at the surface freezes at exactly 0 °C.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_f

      call make_eos(eos)
      t_f = eos_freezing_point(eos, 0.0_wp, 0.0_wp)
      call check(error, abs(t_f) < 1.0e-15_wp, "T_f(0, 0) must be 0")
      call eos%destroy()
   end subroutine test_fresh_zero

   subroutine test_monotonic_s(error)
      !! Strictly decreasing in S: saltier water freezes colder.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_prev, t_cur, s
      integer :: is
      logical :: monotone

      call make_eos(eos)
      monotone = .true.
      t_prev = eos_freezing_point(eos, 0.0_wp, 0.0_wp)
      do is = 1, 40
         s = real(is, wp)
         t_cur = eos_freezing_point(eos, s, 0.0_wp)
         if (t_cur >= t_prev) monotone = .false.
         t_prev = t_cur
      end do
      call check(error, monotone, "T_f must be strictly decreasing in S")
      call eos%destroy()
   end subroutine test_monotonic_s

   subroutine test_pressure(error)
      !! Pressure depression: at p = 1e7 Pa (~1000 m) T_f drops by
      !! TFR_P_COEFF·p = −0.753 °C relative to the surface value.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp), parameter :: P_DEEP = 1.0e7_wp
      real(wp) :: t_sfc, t_deep

      call make_eos(eos)
      t_sfc = eos_freezing_point(eos, 35.0_wp, 0.0_wp)
      t_deep = eos_freezing_point(eos, 35.0_wp, P_DEEP)
      call check(error, abs((t_deep - t_sfc) - TFR_P_COEFF*P_DEEP) < 1.0e-12_wp, &
                 "pressure depression must be TFR_P_COEFF*p")
      if (allocated(error)) return
      call check(error, t_deep < t_sfc, "deep freezing point must be colder")
      call eos%destroy()
   end subroutine test_pressure

   subroutine test_elemental_array(error)
      !! `elemental` contract: one call over an S ARRAY (scalar eos + p
      !! broadcast) returns the per-element scalar results.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: s_arr(5), t_arr(5)
      real(wp) :: max_err
      integer :: k

      call make_eos(eos)
      s_arr = [0.0_wp, 5.0_wp, 20.0_wp, 35.0_wp, 40.0_wp]
      t_arr = eos_freezing_point(eos, s_arr, 0.0_wp)
      max_err = 0.0_wp
      do k = 1, size(s_arr)
         max_err = max(max_err, &
                       abs(t_arr(k) - eos_freezing_point(eos, s_arr(k), 0.0_wp)))
      end do
      call check(error, max_err < 1.0e-15_wp, &
                 "elemental array call must match scalar calls exactly")
      if (allocated(error)) return
      call check(error, abs(t_arr(4) - TFR_S_COEFF*35.0_wp) < 1.0e-12_wp, &
                 "array element S=35 must give -1.89 degC")
      call eos%destroy()
   end subroutine test_elemental_array

   subroutine test_variants(error)
      !! v1 contract: the linear liquidus applies to ALL EOS variants
      !! (matching MOM6's TFREEZE_FORM="LINEAR" default under any density
      !! branch).  When a TEOS-10 branch lands, this test pins the
      !! variants it must NOT change.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_lin, t_wright, t_roquet

      call make_eos(eos)
      eos%variant = EOS_VARIANT_LINEAR
      t_lin = eos_freezing_point(eos, 35.0_wp, 0.0_wp)
      eos%variant = EOS_VARIANT_WRIGHT_97
      t_wright = eos_freezing_point(eos, 35.0_wp, 0.0_wp)
      eos%variant = EOS_VARIANT_ROQUET_SPV
      t_roquet = eos_freezing_point(eos, 35.0_wp, 0.0_wp)
      call check(error, abs(t_lin - t_wright) < 1.0e-15_wp .and. &
                 abs(t_lin - t_roquet) < 1.0e-15_wp, &
                 "v1: every EOS variant must return the linear liquidus")
      call eos%destroy()
   end subroutine test_variants

   ! ---------------------------------------------------------------------
   ! The liquidus coefficient SETS
   ! ---------------------------------------------------------------------

   pure function same_bits(a, b) result(same)
      !! Raw IEEE-754 bit-pattern equality.  `==` on reals would accept a
      !! `−0.0` vs `+0.0` swap silently, and that swap is EXACTLY the one
      !! difference this capability can introduce — so the bit-identity
      !! test has to look below the arithmetic.
      real(wp), intent(in) :: a, b
      logical :: same
      same = transfer(a, 0_int64) == transfer(b, 0_int64)
   end function same_bits

   pure function legacy_liquidus(S, p) result(T_f)
      !! The PRE-KNOB body of `eos_freezing_point`, transcribed verbatim:
      !!
      !!   T_f = TFR_S_COEFF*S + TFR_P_COEFF*p
      !!
      !! Kept as a procedure taking RUNTIME dummies so the sweep values
      !! cannot be constant-folded away; the COEFFICIENTS stay module
      !! `parameter`s because that is what the pre-knob kernel had, and
      !! reproducing the old codegen is the whole point of a reference.
      real(wp), intent(in) :: S, p
      real(wp) :: T_f
      T_f = TFR_S_COEFF*S + TFR_P_COEFF*p
   end function legacy_liquidus

   subroutine test_default_set_bit_identical(error)
      !! (i) THE BIT-IDENTITY GATE, in two arms, because the boundary is
      !! real and was MEASURED rather than assumed.
      !!
      !! ARM A — the production envelope, `p = 0`.  All four callers of
      !! `eos_freezing_point` (`ice_frazil_accumulate`,
      !! `ice_frazil_uptake{,_multicat}_impl`,
      !! `ice_compute_basal_flux_impl`) pass `p = 0.0_wp`, so this arm is
      !! what "bit-identical" means for every shipped namelist.  Over a
      !! dense salinity sweep the handle-driven
      !! `(tfr_s·S + tfr_p·p) + tfr_0` must reproduce the pre-knob
      !! `TFR_S_COEFF*S + TFR_P_COEFF*p` BIT FOR BIT — including through
      !! any FMA contraction, since `fma(λ1, S, ±0)` and
      !! `round(λ1·S) + (±0)` are the same value.
      !!
      !!   The ONE documented exception is the signed zero at S = 0, the
      !!   only point where `T_f` is a zero at all: the legacy expression
      !!   gives `(−0.0) + (−0.0) = −0.0`, adding the `+0.0` intercept
      !!   gives `+0.0`.  Accepted — `−0.0 == +0.0` is true, nothing
      !!   divides by `T_f` or branches on its sign, and every consumer
      !!   uses it only inside `T − T_f`.  The exception is asserted
      !!   EXPLICITLY (values equal AND the new answer is the positive
      !!   zero) so it can never quietly widen to cover a real gap.
      !!
      !! ARM B — OFF the production envelope, `p /= 0`.  Moving the
      !! coefficients from module `parameter`s onto the handle makes them
      !! runtime values, and a toolchain may then contract `λ1·S + λ3·p`
      !! into an FMA where it did not before: gfortran 15.1 at
      !! `-O3 -march=native` does exactly that.  The answer is therefore
      !! allowed to move by AT MOST ONE ULP here, and that bound is what
      !! this arm pins (a formula slip would be orders of magnitude
      !! larger).  No caller reaches this arm today; wiring the cavity
      !! pressure into the liquidus is a later PR.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: p_sweep(4)
      real(wp) :: s, t_new, t_legacy
      integer :: is, ip, n_bad_p0, n_bad_ulp
      integer(int64) :: gap
      logical :: hit_zero_case

      ! Runtime-filled, NOT `parameter`: see `legacy_liquidus`.
      p_sweep = [1.0_wp, 1.0e6_wp, 5.0e6_wp, 2.0e7_wp]

      call make_eos(eos)

      ! Non-vacuity: the handle really is carrying the legacy triple.
      call check(error, eos%tfr_s == TFR_S_COEFF .and. eos%tfr_0 == TFR_0_COEFF &
                 .and. eos%tfr_p == TFR_P_COEFF, &
                 "default eos_t must carry the seaice liquidus triple")
      if (allocated(error)) then
         call eos%destroy()
         return
      end if
      call check(error, TFR_0_COEFF == 0.0_wp, "seaice intercept must be exactly zero")
      if (allocated(error)) then
         call eos%destroy()
         return
      end if

      ! --- Arm A: p = 0, S over [0, 40] in 0.001 steps (40 001 points). ---
      n_bad_p0 = 0
      hit_zero_case = .false.
      do is = 0, 40000
         s = real(is, wp)*1.0e-3_wp
         t_new = eos_freezing_point(eos, s, 0.0_wp)
         t_legacy = legacy_liquidus(s, 0.0_wp)
         if (t_legacy == 0.0_wp) then
            hit_zero_case = .true.
            if (t_new /= t_legacy) n_bad_p0 = n_bad_p0 + 1
            if (.not. same_bits(t_new, 0.0_wp)) n_bad_p0 = n_bad_p0 + 1
            if (.not. same_bits(t_legacy, -0.0_wp)) n_bad_p0 = n_bad_p0 + 1
         else if (.not. same_bits(t_new, t_legacy)) then
            n_bad_p0 = n_bad_p0 + 1
         end if
      end do

      checks: block
         call check(error, n_bad_p0 == 0, &
                    "at p = 0 (every production call site) the default set must be "// &
                    "bit-identical to the legacy liquidus expression")
         if (allocated(error)) exit checks
         call check(error, hit_zero_case, &
                    "sweep must actually reach the S=0, p=0 signed-zero point")
         if (allocated(error)) exit checks

         ! --- Arm B: p /= 0, bounded at one ulp. ---
         n_bad_ulp = 0
         do is = 0, 4000
            s = real(is, wp)*1.0e-2_wp
            do ip = 1, size(p_sweep)
               t_new = eos_freezing_point(eos, s, p_sweep(ip))
               t_legacy = legacy_liquidus(s, p_sweep(ip))
               gap = abs(transfer(t_new, 0_int64) - transfer(t_legacy, 0_int64))
               if (gap > 1_int64) n_bad_ulp = n_bad_ulp + 1
            end do
         end do
         call check(error, n_bad_ulp == 0, &
                    "at p /= 0 the default set must stay within one ulp of the legacy "// &
                    "expression (FMA-contraction difference, not a formula change)")
      end block checks

      call eos%destroy()
   end subroutine test_default_set_bit_identical

   subroutine test_isomip_hand_values(error)
      !! (ii) The ISOMIP+ set against hand-computed values from
      !! Asay-Davis et al. (2016) Table 4 / eq. (25):
      !!   T_f(34.5 PSU, 0 Pa)     = −0.0573·34.5 + 0.0832 = −1.89365 °C
      !!   T_f(34.5 PSU, 5.0e6 Pa) = −1.89365 − 0.3765     = −2.27015 °C
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_f

      call make_eos(eos)
      call eos_apply_tfreeze_set(eos, TFREEZE_SET_ISOMIP)

      checks: block
         call check(error, eos%tfr_s == TFR_ISOMIP_S_COEFF .and. &
                    eos%tfr_0 == TFR_ISOMIP_0_COEFF .and. &
                    eos%tfr_p == TFR_ISOMIP_P_COEFF, &
                    "isomip set must land the Table 4 triple on the handle")
         if (allocated(error)) exit checks

         t_f = eos_freezing_point(eos, 34.5_wp, 0.0_wp)
         call check(error, abs(t_f - ISOMIP_TF_S345_P0) < 1.0e-13_wp, &
                    "ISOMIP+ T_f(34.5, 0) must be -1.89365 degC")
         if (allocated(error)) exit checks

         t_f = eos_freezing_point(eos, 34.5_wp, 5.0e6_wp)
         call check(error, abs(t_f - ISOMIP_TF_S345_P5E6) < 1.0e-13_wp, &
                    "ISOMIP+ T_f(34.5, 5e6 Pa) must be -2.27015 degC")
         if (allocated(error)) exit checks

         ! Non-vacuity: the DEFAULT set must NOT reproduce these numbers
         ! (else the test would pass with the knob unwired).
         call eos_apply_tfreeze_set(eos, TFREEZE_SET_SEAICE)
         t_f = eos_freezing_point(eos, 34.5_wp, 0.0_wp)
         call check(error, abs(t_f - ISOMIP_TF_S345_P0) > 1.0e-3_wp, &
                    "the seaice set must be resolvably different from ISOMIP+")
      end block checks

      call eos%destroy()
   end subroutine test_isomip_hand_values

   subroutine test_isomip_oracle(error)
      !! (ii, second arm) Agreement with the independent Python prototype
      !! oracle.  Cases `liq_isomip__mild_deep_mid`,
      !! `jenkins10_native__mild_deep_mid` and `liq_isomip__cold_deep_slow`
      !! of `ice_shelf_melt/oracle.json` (prototype git commit
      !! 38cbe556772edb96a7b55fb4756329d9aed7eed7); their
      !! `outputs.T_freeze_far` is `tfreeze(S_w, p_b)` under the `isomip`
      !! liquidus.  Tolerance 1e-13 °C — the two evaluation orders can
      !! differ only in the last bit or two.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos
      real(wp) :: t_f, max_err
      integer :: k

      call make_eos(eos)
      call eos_apply_tfreeze_set(eos, TFREEZE_SET_ISOMIP)

      max_err = 0.0_wp
      do k = 1, size(ORACLE_S)
         t_f = eos_freezing_point(eos, ORACLE_S(k), ORACLE_P(k))
         max_err = max(max_err, abs(t_f - ORACLE_TF(k)))
      end do

      call check(error, max_err < ORACLE_TOL, &
                 "ISOMIP+ liquidus must match the ice_shelf_melt oracle to 1e-13 degC")
      call eos%destroy()
   end subroutine test_isomip_oracle

   subroutine test_set_difference(error)
      !! (iii) The two sets differ by the closed form
      !!
      !!   T_f^isomip − T_f^seaice = (λ1^iso − λ1^sea)·S + λ2^iso
      !!                           = −0.0033·S + 0.0832
      !!
      !! — INDEPENDENT of p, because both sets share λ3 = −7.53e-8.  At
      !! S = 34.5 that is −0.0307 °C, the ~0.03 °C offset that can flip
      !! the sign of an ice-shelf basal melt rate.  The p-independence is
      !! asserted too: it is what says the pressure depression has not
      !! been accidentally re-scaled along with the salinity slope.
      type(error_type), allocatable, intent(out) :: error
      type(eos_t) :: eos_sea, eos_iso
      real(wp), parameter :: S_SWEEP(4) = [0.0_wp, 30.0_wp, 34.5_wp, 40.0_wp]
      real(wp), parameter :: P_SWEEP(3) = [0.0_wp, 4.5e6_wp, 2.0e7_wp]
      real(wp) :: delta, expected, spread_lo, spread_hi
      integer :: is, ip
      logical :: ok

      call make_eos(eos_sea)
      call make_eos(eos_iso)
      call eos_apply_tfreeze_set(eos_sea, TFREEZE_SET_SEAICE)
      call eos_apply_tfreeze_set(eos_iso, TFREEZE_SET_ISOMIP)

      ok = .true.
      do is = 1, size(S_SWEEP)
         expected = (TFR_ISOMIP_S_COEFF - TFR_S_COEFF)*S_SWEEP(is) + TFR_ISOMIP_0_COEFF
         do ip = 1, size(P_SWEEP)
            delta = eos_freezing_point(eos_iso, S_SWEEP(is), P_SWEEP(ip)) &
                    - eos_freezing_point(eos_sea, S_SWEEP(is), P_SWEEP(ip))
            if (abs(delta - expected) > 1.0e-13_wp) ok = .false.
         end do
      end do

      checks: block
         call check(error, ok, &
                    "set-to-set difference must be (dlambda1)*S + lambda2, p-independent")
         if (allocated(error)) exit checks

         ! The magnitude that motivates the knob: ~0.03 degC at shelf
         ! salinity, bracketed rather than pinned to a literal.
         delta = eos_freezing_point(eos_iso, 34.5_wp, 4.5e6_wp) &
                 - eos_freezing_point(eos_sea, 34.5_wp, 4.5e6_wp)
         spread_lo = 0.030_wp
         spread_hi = 0.031_wp
         call check(error, abs(delta) > spread_lo .and. abs(delta) < spread_hi, &
                    "at S=34.5 the two liquidi must differ by ~0.0307 degC")
      end block checks

      call eos_sea%destroy()
      call eos_iso%destroy()
   end subroutine test_set_difference

   subroutine test_tfreeze_set_parse(error)
      !! (iv, first arm) The `pure` parser is the testable surface of the
      !! fail-loud path (`validate_config` `error stop`s).  Every valid
      !! spelling round-trips; a typo is INVALID, NOT a silent fallback to
      !! the default — the whole point, since a mistyped liquidus has no
      !! run-time symptom.
      type(error_type), allocatable, intent(out) :: error

      checks: block
         call check(error, parse_tfreeze_set("seaice") == TFREEZE_SET_SEAICE, &
                    "'seaice' -> TFREEZE_SET_SEAICE")
         if (allocated(error)) exit checks
         call check(error, parse_tfreeze_set("isomip") == TFREEZE_SET_ISOMIP, &
                    "'isomip' -> TFREEZE_SET_ISOMIP")
         if (allocated(error)) exit checks
         call check(error, parse_tfreeze_set(" ISOMIP ") == TFREEZE_SET_ISOMIP, &
                    "parser must trim + accept upper case")
         if (allocated(error)) exit checks
         call check(error, parse_tfreeze_set("nonsense") == TFREEZE_SET_INVALID, &
                    "typo -> TFREEZE_SET_INVALID (never a silent default)")
         if (allocated(error)) exit checks
         call check(error, parse_tfreeze_set("") == TFREEZE_SET_INVALID, &
                    "empty string -> TFREEZE_SET_INVALID")
         if (allocated(error)) exit checks
         ! An INVALID code must leave the handle alone — the abort belongs
         ! to validate_config, and `eos_apply_tfreeze_set` is pure.
         handle: block
            type(eos_t) :: eos
            call make_eos(eos)
            call eos_apply_tfreeze_set(eos, TFREEZE_SET_INVALID)
            call check(error, eos%tfr_s == TFR_S_COEFF .and. eos%tfr_0 == TFR_0_COEFF &
                       .and. eos%tfr_p == TFR_P_COEFF, &
                       "INVALID must leave the handle untouched")
            call eos%destroy()
         end block handle
      end block checks
   end subroutine test_tfreeze_set_parse

   subroutine test_tfreeze_set_fail_loud(error)
      !! (iv, second arm) …and the belt-and-braces guard in
      !! `validate_config` actually fires.  Baseline first, so a failure
      !! can only come from the one key this test moves.
      type(error_type), allocatable, intent(out) :: error
      type(config_t) :: cfg
      integer :: ierr

      ierr = -999
      call validate_config(cfg, ierr=ierr)
      call check(error, ierr == OCEAN_STATUS_OK, &
                 "default config must validate cleanly (fail-loud baseline)")
      if (allocated(error)) return

      cfg%ocean%eos%tfreeze_set = "millero78"
      ierr = -999
      call validate_config(cfg, ierr=ierr)
      call check(error, ierr == OCEAN_STATUS_ERR_CONFIG_VALIDATE, &
                 "an unrecognised &ocean_eos_nml tfreeze_set must fail loud")
      if (allocated(error)) return

      ! …and a recognised one still validates.
      cfg%ocean%eos%tfreeze_set = "isomip"
      ierr = -999
      call validate_config(cfg, ierr=ierr)
      call check(error, ierr == OCEAN_STATUS_OK, &
                 "tfreeze_set = 'isomip' must validate")
   end subroutine test_tfreeze_set_fail_loud

   subroutine test_configured_set_reaches_ice_handle(error)
      !! (v) THE PLUMBING TEST.  The sea-ice kernels (`ice_frazil_*`,
      !! `ice_compute_basal_flux`) are handed `engine%state%eos` — the
      !! god-state handle itself, not a slot copy — so this asserts that
      !! the production configure path lands the configured set on THAT
      !! object, and that `eos_freezing_point` called through it returns
      !! the ISOMIP+ answer.  `configure_ocean_drag` is the earliest
      !! `configure_ocean_*` stage and the one that owns the assignment;
      !! it runs before `configure_ocean_lateral`, which copies the whole
      !! flat-POD handle onto `vmix%eos` / `epbl%eos` / `kshear%eos` /
      !! `tidal_mixing%eos`, and before `ocean_state_enter_data`.
      type(error_type), allocatable, intent(out) :: error
      type(config_t) :: cfg
      type(hgrid_t) :: grid
      type(ocean_state_t) :: state
      real(wp) :: t_f

      cfg%sim_type = "ocean"
      cfg%nx = 6
      cfg%ny = 5
      cfg%dx = 1000.0_wp
      cfg%dy = 1000.0_wp
      cfg%nz_layers = 2
      cfg%nghost = 2
      cfg%ocean%eos%tfreeze_set = "isomip"

      call grid%init(6, 5, 2, 1000.0_wp, 1000.0_wp)
      call state%init_from_config(cfg, grid)

      ! Non-vacuity: before configure the handle still carries the
      ! sea-ice default, so a dropped assignment cannot hide.
      checks: block
         call check(error, state%eos%tfr_s == TFR_S_COEFF, &
                    "pre-configure handle must still hold the seaice slope")
         if (allocated(error)) exit checks

         call configure_ocean_drag(cfg, state, compute_rank=0)

         call check(error, state%eos%tfr_s == TFR_ISOMIP_S_COEFF .and. &
                    state%eos%tfr_0 == TFR_ISOMIP_0_COEFF .and. &
                    state%eos%tfr_p == TFR_ISOMIP_P_COEFF, &
                    "&ocean_eos_nml tfreeze_set must reach ocean_state%eos")
         if (allocated(error)) exit checks

         ! The call the ice kernels make, through the very handle they get.
         t_f = eos_freezing_point(state%eos, 34.5_wp, 0.0_wp)
         call check(error, abs(t_f - ISOMIP_TF_S345_P0) < 1.0e-13_wp, &
                    "eos_freezing_point through the configured state handle "// &
                    "must return the ISOMIP+ value")
      end block checks

      call state%destroy()
   end subroutine test_configured_set_reaches_ice_handle

end module test_ocean_freezing_point
