!! Unit + analytical tests for the energetics-based PBL
!! (`rdb_ocean_epbl`).  Golden values generated by a Python reference
!! prototype of the RH18 energetics solve.
!!
!! Cases:
!!   * Wright/linear dSV derivatives vs centred finite differences.
!!   * OM4 mstar formula hand-check.
!!   * Surface-seed identity: pure cooling gives the convective
!!     ledger term nstar * (-0.5 rho0 h_sfc B0) exactly.
!!   * Kraus-Turner wind deepening: f = 0, linear N², constant u*;
!!     MLD grows as (12 mstar u*^3 t / N²)^(1/3) — exponent + a
!!     prefactor band that accounts for the transition-layer shape.
!!   * TKE budget closure to round-off under combined wind + cooling.
!!   * Stabilizing surface flux shoals the MLD vs the neutral run.
!!   * Convective deepening tracks the encroachment scale when the
!!     cooling is actually applied to T (production ordering:
!!     surface flux -> EPBL -> implicit diffusion).
module test_ocean_epbl
   use testdrive, only: new_unittest, unittest_type, error_type, check
   use rdb_constants, only: wp, GRAVITY
   use rdb_grid, only: hgrid_t
   use rdb_multilayer_state, only: multilayer_state_t
   use rdb_ocean_epbl, only: ocean_epbl_t, epbl_compute, epbl_find_mstar, &
                             epbl_lf17_wave_state, epbl_lf17_la, epbl_lt_enhance, &
                             EPBL_MSTAR_CONSTANT, EPBL_MSTAR_OM4, EPBL_LT_RESCALE
   use rdb_eos, only: eos_t, eos_specvol_derivs, eos_density_point, &
                      EOS_VARIANT_LINEAR, EOS_VARIANT_WRIGHT_97
   use rdb_ocean_surface_stress, only: ocean_surface_stress_t
   use rdb_ocean_surface_flux, only: ocean_surface_flux_t, SEAWATER_CP, &
                                     ocean_surface_flux_apply_tracers
   use rdb_ocean_vdiff, only: ocean_vdiff_t, vdiff_apply_tracers
   implicit none
   private

   public :: collect_ocean_epbl_tests

   integer, parameter :: NGHOST = 2
   real(wp), parameter :: RHO0 = 1035.0_wp
   real(wp), parameter :: ALPHA_LIN = 0.2_wp   ! kg/m^3/K (realistic)
   real(wp), parameter :: BETA_LIN = 0.8_wp    ! kg/m^3/PSU

contains

   subroutine collect_ocean_epbl_tests(testsuite)
      type(unittest_type), allocatable, intent(out) :: testsuite(:)

      testsuite = [ &
                  new_unittest("epbl_dsv_derivs_match_finite_difference", test_dsv_fd), &
                  new_unittest("epbl_mstar_om4_formula", test_mstar_om4), &
                  new_unittest("epbl_ctke_seed_identity", test_ctke_seed), &
                  new_unittest("epbl_wind_deepening_kraus_turner", test_wind_deepening), &
                  new_unittest("epbl_tke_budget_closes", test_budget_closure), &
                  new_unittest("epbl_stable_flux_shoals_mld", test_stable_shoals), &
                  new_unittest("epbl_convective_deepening", test_convective), &
                  new_unittest("epbl_lf17_la_spot_values", test_lf17_spot), &
                  new_unittest("epbl_lt_enhancement_monotone", test_lt_monotone), &
                  new_unittest("epbl_lt_deepens_wind_mixing", test_lt_deepens) &
                  ]
   end subroutine collect_ocean_epbl_tests

   ! -----------------------------------------------------------------
   ! Helpers
   ! -----------------------------------------------------------------

   subroutine make_grid(grid, nx_phys, ny_phys)
      type(hgrid_t), intent(out) :: grid
      integer, intent(in) :: nx_phys, ny_phys
      call grid%init(nx_phys, ny_phys, NGHOST, 1.0_wp, 1.0_wp)
   end subroutine make_grid

   subroutine setup_epbl(epbl, grid, nz)
      !! Default analytical-test configuration: linear EOS with
      !! realistic sensitivities, constant mstar, cube-root vstar,
      !! f = 0 (set_f_centre overrides where a test needs rotation).
      type(ocean_epbl_t), intent(inout) :: epbl
      type(hgrid_t), intent(in) :: grid
      integer, intent(in) :: nz
      call epbl%init(grid, nz_ml=nz)
      epbl%enable = .true.
      epbl%mstar_scheme = EPBL_MSTAR_CONSTANT
      epbl%mstar_const = 1.2_wp
      epbl%nstar = 0.2_wp
      epbl%eos%variant = EOS_VARIANT_LINEAR
      epbl%eos%alpha_T = ALPHA_LIN
      epbl%eos%beta_S = BETA_LIN
      epbl%eos%rho0 = RHO0
      epbl%rho0 = RHO0
      epbl%f_centre = 0.0_wp
      epbl%tke_diags = .true.
   end subroutine setup_epbl

   subroutine setup_stratified_T(ms, nz, dz, t_surf, dT_dz)
      !! Linear temperature stratification: T(k) decreases downward
      !! from `t_surf` at the surface layer (k = nz) with gradient
      !! dT_dz (K/m, positive = stable for alpha > 0).  Uniform S.
      type(multilayer_state_t), intent(inout) :: ms
      integer, intent(in) :: nz
      real(wp), intent(in) :: dz, t_surf, dT_dz
      integer :: k
      real(wp) :: z_below_surf, t_k

      ms%h_layer = dz
      ms%u_face_x_layer = 0.0_wp
      ms%v_face_y_layer = 0.0_wp
      do k = 1, nz
         ! depth of layer-k centre below the surface
         z_below_surf = (real(nz - k, wp) + 0.5_wp)*dz
         t_k = t_surf - dT_dz*z_below_surf
         ms%tracers(ms%idx_temperature)%hTr(:, :, k) = t_k*dz
         ms%tracers(ms%idx_salinity)%hTr(:, :, k) = 35.0_wp*dz
      end do
   end subroutine setup_stratified_T

   subroutine run_epbl_steps(grid, ms, epbl, ss, sf, vd, dt, n_steps, &
                             mld_series, t_series, sample_every)
      !! Drive the production sequence per step on device:
      !!   surface flux into T -> EPBL -> implicit T/S diffusion
      !! with EPBL's kd_int as the tracer diffusivity.  Samples
      !! `epbl%mld` at the probe column every `sample_every` steps.
      type(hgrid_t), intent(in) :: grid
      type(multilayer_state_t), intent(inout) :: ms
      type(ocean_epbl_t), intent(inout) :: epbl
      type(ocean_surface_stress_t), intent(inout) :: ss
      type(ocean_surface_flux_t), intent(inout) :: sf
         !! inout: enter_data / exit_data map Q_heat/Q_salt to device
      type(ocean_vdiff_t), intent(inout) :: vd
      real(wp), intent(in) :: dt
      integer, intent(in) :: n_steps, sample_every
      real(wp), intent(out) :: mld_series(:), t_series(:)

      integer :: step, n_sample, i_probe, j_probe

      i_probe = grid%nx_total/2
      j_probe = grid%ny_total/2
      n_sample = 0

      !$acc enter data copyin(ms, epbl, ss, sf, vd)
      call ms%enter_data()
      call sf%enter_data()
      call epbl%enter_data()
      call vd%enter_data()
      do step = 1, n_steps
         call ocean_surface_flux_apply_tracers(grid, sf, ms, dt, active=.true.)
         call epbl_compute(grid, epbl, ms, ss, dt, sf=sf)
         call vdiff_apply_tracers(grid, vd, ms, dt, kt_source=epbl%kd_int)
         if (mod(step, sample_every) == 0 .and. n_sample < size(mld_series)) then
            n_sample = n_sample + 1
            !$acc update self(epbl%mld)
            mld_series(n_sample) = epbl%mld(i_probe, j_probe)
            t_series(n_sample) = real(step, wp)*dt
         end if
      end do
      !$acc update self(epbl%mld, epbl%kd_int, epbl%la)
      !$acc update self(epbl%tke_wind, epbl%tke_conv)
      !$acc update self(epbl%tke_forcing, epbl%tke_mixing)
      !$acc update self(epbl%tke_mech_decay, epbl%tke_conv_decay)
      call vd%exit_data()
      call epbl%exit_data()
      call sf%exit_data()
      call ms%exit_data()
      !$acc exit data delete(ms, epbl, ss, sf, vd)
   end subroutine run_epbl_steps

   pure subroutine fit_loglog_slope(t_series, d_series, n, slope)
      !! Least-squares slope of log(D) vs log(t).
      real(wp), intent(in) :: t_series(:), d_series(:)
      integer, intent(in) :: n
      real(wp), intent(out) :: slope
      real(wp) :: x_mean, y_mean, sxy, sxx, x, y
      integer :: m

      x_mean = 0.0_wp
      y_mean = 0.0_wp
      do m = 1, n
         x_mean = x_mean + log(t_series(m))
         y_mean = y_mean + log(d_series(m))
      end do
      x_mean = x_mean/real(n, wp)
      y_mean = y_mean/real(n, wp)
      sxy = 0.0_wp
      sxx = 0.0_wp
      do m = 1, n
         x = log(t_series(m)) - x_mean
         y = log(d_series(m)) - y_mean
         sxy = sxy + x*y
         sxx = sxx + x*x
      end do
      slope = sxy/sxx
   end subroutine fit_loglog_slope

   ! -----------------------------------------------------------------
   ! Cases
   ! -----------------------------------------------------------------

   subroutine test_dsv_fd(error)
      !! eos_specvol_derivs vs centred finite differences of
      !! 1/eos_density_point, for Wright (three (T,S,p) points) and
      !! linear (exact).
      type(error_type), allocatable, intent(out) :: error
      real(wp), parameter :: T_PTS(3) = [2.0_wp, 10.0_wp, 25.0_wp]
      real(wp), parameter :: S_PTS(3) = [33.0_wp, 35.0_wp, 37.5_wp]
      real(wp), parameter :: P_PTS(3) = [0.0_wp, 2.0e6_wp, 4.0e7_wp]
      real(wp), parameter :: EPS_T = 1.0e-4_wp, EPS_S = 1.0e-4_wp
      real(wp) :: dsv_dt, dsv_ds, fd_dt, fd_ds, sv_p, sv_m
      type(eos_t) :: eos_w, eos_l
      integer :: n
      eos_w%variant = EOS_VARIANT_WRIGHT_97
      eos_w%rho0 = RHO0; eos_w%alpha_T = ALPHA_LIN; eos_w%beta_S = BETA_LIN
      eos_l%variant = EOS_VARIANT_LINEAR
      eos_l%rho0 = RHO0; eos_l%alpha_T = ALPHA_LIN; eos_l%beta_S = BETA_LIN
      checks: block
         do n = 1, 3
            call eos_specvol_derivs(eos_w, T_PTS(n), S_PTS(n), P_PTS(n), &
                                    dsv_dt, dsv_ds)
            sv_p = 1.0_wp/eos_density_point(eos_w, T_PTS(n) + EPS_T, S_PTS(n), P_PTS(n))
            sv_m = 1.0_wp/eos_density_point(eos_w, T_PTS(n) - EPS_T, S_PTS(n), P_PTS(n))
            fd_dt = (sv_p - sv_m)/(2.0_wp*EPS_T)
            sv_p = 1.0_wp/eos_density_point(eos_w, T_PTS(n), S_PTS(n) + EPS_S, P_PTS(n))
            sv_m = 1.0_wp/eos_density_point(eos_w, T_PTS(n), S_PTS(n) - EPS_S, P_PTS(n))
            fd_ds = (sv_p - sv_m)/(2.0_wp*EPS_S)
            call check(error, abs(dsv_dt - fd_dt) < 1.0e-7_wp*abs(fd_dt), &
                       "Wright dSV/dT disagrees with finite difference")
            if (allocated(error)) exit checks
            call check(error, abs(dsv_ds - fd_ds) < 1.0e-7_wp*abs(fd_ds), &
                       "Wright dSV/dS disagrees with finite difference")
            if (allocated(error)) exit checks
         end do
         ! Linear: exact closed forms.
         call eos_specvol_derivs(eos_l, 10.0_wp, 35.0_wp, 0.0_wp, dsv_dt, dsv_ds)
         call check(error, abs(dsv_dt - ALPHA_LIN/RHO0**2) < 1.0e-20_wp, &
                    "linear dSV/dT mismatch")
         if (allocated(error)) exit checks
         call check(error, abs(dsv_ds + BETA_LIN/RHO0**2) < 1.0e-20_wp, &
                    "linear dSV/dS mismatch")
      end block checks
   end subroutine test_dsv_fd

   subroutine test_mstar_om4(error)
      !! OM4 mstar hand-check: stabilizing term mstar_coef1 *
      !! sqrt(B0/(u*^2 f)), Ekman term c_ek*log(u*/(f*BLD)) capped at
      !! 1.25, max of the two.
      type(error_type), allocatable, intent(out) :: error
      real(wp), parameter :: USTAR = 0.01_wp, ABSF = 1.0e-4_wp, BLD = 50.0_wp
      real(wp) :: mstar, expected_n, expected_s, b0
      checks: block
         ! Neutral: B0 = 0 -> Ekman term only.
         call epbl_find_mstar(EPBL_MSTAR_OM4, 1.2_wp, -1.0_wp, 0.3_wp, &
                              0.085_wp, 0.0_wp, &
                              0.275_wp, 8.0_wp, -5.0_wp, 0.2_wp, 0.4_wp, &
                              0.0_wp, USTAR, BLD, ABSF, mstar)
         expected_n = min(1.25_wp, 0.085_wp*log(USTAR/(ABSF*BLD)))
         call check(error, abs(mstar - expected_n) < 1.0e-14_wp, &
                    "OM4 neutral mstar mismatch")
         if (allocated(error)) exit checks
         ! Strongly stabilizing: mstar_S dominates.
         b0 = 1.0e-6_wp
         call epbl_find_mstar(EPBL_MSTAR_OM4, 1.2_wp, -1.0_wp, 0.3_wp, &
                              0.085_wp, 0.0_wp, &
                              0.275_wp, 8.0_wp, -5.0_wp, 0.2_wp, 0.4_wp, &
                              b0, USTAR, BLD, ABSF, mstar)
         expected_s = 0.3_wp*sqrt(b0/(USTAR**2*ABSF))
         call check(error, abs(mstar - max(expected_s, expected_n)) < 1.0e-14_wp, &
                    "OM4 stabilizing mstar mismatch")
         if (allocated(error)) exit checks
         ! Constant scheme ignores everything.
         call epbl_find_mstar(EPBL_MSTAR_CONSTANT, 1.2_wp, -1.0_wp, 0.3_wp, &
                              0.085_wp, 0.0_wp, &
                              0.275_wp, 8.0_wp, -5.0_wp, 0.2_wp, 0.4_wp, &
                              b0, USTAR, BLD, ABSF, mstar)
         call check(error, abs(mstar - 1.2_wp) < 1.0e-15_wp, &
                    "constant mstar mismatch")
      end block checks
   end subroutine test_mstar_om4

   subroutine test_ctke_seed(error)
      !! Pure cooling, no wind, first call on a stable column: the
      !! convective ledger term must equal nstar * (-0.5 rho0 h_sfc
      !! B0) with B0 = g alpha q_T / rho0 (linear EOS) — verifies the
      !! surface-seed energetics + sign conventions end to end.  Also
      !! checks the boundary interfaces stay at zero.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 8
      real(wp), parameter :: DZ = 5.0_wp, DT = 1800.0_wp
      real(wp), parameter :: Q_HEAT = -200.0_wp
      real(wp) :: mld_series(1), t_series(1)
      real(wp) :: q_t_kin, b0, ctke_expected, conv_expected
      integer :: i_probe, j_probe
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_epbl(epbl, grid, NZ)
         call ss%init(grid)
         call ss%set_wind_stress_const(0.0_wp, 0.0_wp)
         call sf%init(grid)
         call sf%set_surface_flux_const(Q_HEAT, 0.0_wp)
         call vd%init(grid, nz_ml=NZ)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, 0.05_wp)

         ! Single step.  NOTE: the flux is applied to T BEFORE EPBL
         ! (production ordering), so the surface layer is already
         ! cooled by dt*q_T when the seed is computed — the seed
         ! itself describes that just-applied flux.
         call run_epbl_steps(grid, ms, epbl, ss, sf, vd, DT, 1, &
                             mld_series, t_series, sample_every=1)

         i_probe = grid%nx_total/2
         j_probe = grid%ny_total/2
         q_t_kin = Q_HEAT/(RHO0*SEAWATER_CP)
         b0 = GRAVITY*ALPHA_LIN*q_t_kin/RHO0
         ctke_expected = -0.5_wp*RHO0*DZ*b0*DT
         conv_expected = epbl%nstar*ctke_expected/DT

         call check(error, ctke_expected > 0.0_wp, &
                    "test setup: cooling must release PE")
         if (allocated(error)) exit checks
         call check(error, abs(epbl%tke_conv(i_probe, j_probe) - conv_expected) &
                    < 1.0e-10_wp*conv_expected, &
                    "convective seed != nstar*(-0.5 rho0 h B0)")
         if (allocated(error)) exit checks
         call check(error, abs(epbl%kd_int(i_probe, j_probe, 1)) < 1.0e-30_wp, &
                    "bed interface kd must be zero")
         if (allocated(error)) exit checks
         call check(error, abs(epbl%kd_int(i_probe, j_probe, NZ + 1)) < 1.0e-30_wp, &
                    "surface interface kd must be zero")
      end block checks
      call vd%destroy(); call sf%destroy(); call ss%destroy()
      call epbl%destroy(); call ms%destroy()
   end subroutine test_ctke_seed

   subroutine test_wind_deepening(error)
      !! Kraus-Turner limit: f = 0 (no TKE decay, no Ekman rolloff),
      !! linear N² = 1e-4, u* = 0.01 m/s, no surface buoyancy flux,
      !! constant mstar.  Energetics: mixing a linear profile to
      !! depth D costs rho0 N² D³/12, wind supplies mstar rho0 u*³ t,
      !! so D(t) = (12 mstar u*³ t / N²)^(1/3).  The transition-layer
      !! shape function pushes the realized MLD above the ideal value
      !! (prototype: 1.33x) — assert the exponent tightly and the
      !! prefactor within a generous band.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 100
      real(wp), parameter :: DZ = 3.0_wp, DT = 1800.0_wp
      real(wp), parameter :: USTAR = 0.01_wp
      real(wp), parameter :: N2 = 1.0e-4_wp
      integer, parameter :: N_STEPS = 240          ! 5 days
      integer, parameter :: N_SAMPLE = 20
      real(wp) :: mld_series(N_SAMPLE), t_series(N_SAMPLE)
      real(wp) :: dT_dz, d_analytic, slope, ratio
      integer :: m
      logical :: monotone
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_epbl(epbl, grid, NZ)
         call ss%init(grid)
         call ss%set_wind_stress_const(RHO0*USTAR**2, 0.0_wp)
         call sf%init(grid)            ! zero fluxes
         call vd%init(grid, nz_ml=NZ)
         dT_dz = N2*RHO0/(GRAVITY*ALPHA_LIN)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)

         call run_epbl_steps(grid, ms, epbl, ss, sf, vd, DT, N_STEPS, &
                             mld_series, t_series, sample_every=N_STEPS/N_SAMPLE)

         monotone = .true.
         do m = 2, N_SAMPLE
            if (mld_series(m) < mld_series(m - 1) - 1.0e-9_wp) monotone = .false.
         end do
         call check(error, monotone, "wind-driven MLD must grow monotonically")
         if (allocated(error)) exit checks

         ! Exponent over the second half (early samples carry the
         ! half-depth first-guess transient).
         call fit_loglog_slope(t_series(N_SAMPLE/2:), mld_series(N_SAMPLE/2:), &
                               N_SAMPLE - N_SAMPLE/2 + 1, slope)
         call check(error, slope > 0.20_wp .and. slope < 0.47_wp, &
                    "Kraus-Turner exponent outside [0.20, 0.47]")
         if (allocated(error)) exit checks

         d_analytic = (12.0_wp*epbl%mstar_const*USTAR**3* &
                       t_series(N_SAMPLE)/N2)**(1.0_wp/3.0_wp)
         ratio = mld_series(N_SAMPLE)/d_analytic
         call check(error, ratio > 0.9_wp .and. ratio < 1.8_wp, &
                    "Kraus-Turner prefactor outside [0.9, 1.8] of analytic")
      end block checks
      call vd%destroy(); call sf%destroy(); call ss%destroy()
      call epbl%destroy(); call ms%destroy()
   end subroutine test_wind_deepening

   subroutine test_budget_closure(error)
      !! Combined wind + cooling on a rotating column: the column TKE
      !! ledger must close to round-off every step:
      !!   wind + conv + forcing - mixing - mech_decay - conv_decay = 0
      !! (forcing <= 0; the leftover stocks at the bed are folded into
      !! the decay terms).  This validates the whole bookkeeping
      !! incl. the proportional-drain and rotation-reduction paths.
      !!
      !! (PR-21) Extended with penetrating shortwave via the `q_sw` source
      !! (`q_sw > 0` while `Q_heat < 0` — sunny-but-net-cooling), so the
      !! ledger carries `d_forcing`/`d_mixing`/`d_cdecay` increments from
      !! the sub-surface SW TKE drain (steps 2 + 3b of epbl_column_kernel)
      !! in addition to the surface seed.  The closure must still hold to
      !! round-off — every drain branch posts its ledger increment.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 40
      real(wp), parameter :: DZ = 5.0_wp, DT = 1800.0_wp
      integer, parameter :: N_STEPS = 12
      real(wp) :: mld_series(N_STEPS), t_series(N_STEPS)
      real(wp) :: residual, scale_ref
      integer :: i, j
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_epbl(epbl, grid, NZ)
         call epbl%set_f_centre(grid, 1.0e-4_wp, 0.0_wp, 0.0_wp)
         call ss%init(grid)
         call ss%set_wind_stress_const(0.1_wp, 0.0_wp)
         call sf%init(grid)
         call sf%set_surface_flux_const(-300.0_wp, 0.0_wp)
         ! (PR-21) penetrating shortwave via q_sw (>0) while Q_heat<0:
         ! I0>0 ⇒ ctke_sw<0 ⇒ the sub-surface TKE drain (step 3b) fires,
         ! posting into d_forcing / d_mixing / d_cdecay.
         call sf%set_components(grid, .true.)
         sf%q_sw = 250.0_wp
         call sf%set_sw_penetration(1.0_wp, 0.58_wp, 0.35_wp, 23.0_wp, sw_source="q_sw")
         epbl%epbl_sw_ctke = .true.
         call vd%init(grid, nz_ml=NZ)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, 0.0527_wp)

         ! The budget arrays hold the LAST step's ledger; running
         ! several steps exercises seeds, drains and decays across a
         ! deepening, then we assert the final step's closure at
         ! every interior column.
         call run_epbl_steps(grid, ms, epbl, ss, sf, vd, DT, N_STEPS, &
                             mld_series, t_series, sample_every=1)

         do j = NGHOST + 1, grid%ny_total - NGHOST
            do i = NGHOST + 1, grid%nx_total - NGHOST
               residual = epbl%tke_wind(i, j) + epbl%tke_conv(i, j) + &
                          epbl%tke_forcing(i, j) - epbl%tke_mixing(i, j) - &
                          epbl%tke_mech_decay(i, j) - epbl%tke_conv_decay(i, j)
               scale_ref = epbl%tke_wind(i, j) + epbl%tke_conv(i, j) + &
                           abs(epbl%tke_forcing(i, j)) + 1.0e-30_wp
               call check(error, abs(residual) < 1.0e-9_wp*scale_ref, &
                          "TKE budget ledger does not close")
               if (allocated(error)) exit checks
            end do
         end do
         ! Sanity: with wind + cooling both source terms are active.
         i = grid%nx_total/2
         j = grid%ny_total/2
         call check(error, epbl%tke_wind(i, j) > 0.0_wp, "wind term inactive")
         if (allocated(error)) exit checks
         call check(error, epbl%tke_conv(i, j) > 0.0_wp, "conv term inactive")
      end block checks
      call vd%destroy(); call sf%destroy(); call ss%destroy()
      call epbl%destroy(); call ms%destroy()
   end subroutine test_budget_closure

   subroutine test_stable_shoals(error)
      !! Strong stabilizing (warming) surface flux + the same wind
      !! must produce a clearly shallower MLD than the neutral run
      !! (the warming both drains TKE at the seed and stiffens the
      !! near-surface stratification).
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl_neutral, epbl_stable
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf_neutral, sf_stable
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 60
      real(wp), parameter :: DZ = 3.0_wp, DT = 1800.0_wp
      integer, parameter :: N_STEPS = 96           ! 2 days
      real(wp) :: mld_a(4), mld_b(4), t_s(4), dT_dz
      integer :: i_probe, j_probe
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call ss%init(grid)
         call ss%set_wind_stress_const(RHO0*0.01_wp**2, 0.0_wp)
         call sf_neutral%init(grid)
         call sf_stable%init(grid)
         call sf_stable%set_surface_flux_const(500.0_wp, 0.0_wp)
         call vd%init(grid, nz_ml=NZ)
         dT_dz = 1.0e-4_wp*RHO0/(GRAVITY*ALPHA_LIN)
         i_probe = grid%nx_total/2
         j_probe = grid%ny_total/2

         call setup_epbl(epbl_neutral, grid, NZ)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)
         call run_epbl_steps(grid, ms, epbl_neutral, ss, sf_neutral, vd, DT, &
                             N_STEPS, mld_a, t_s, sample_every=N_STEPS/4)

         call setup_epbl(epbl_stable, grid, NZ)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)
         call run_epbl_steps(grid, ms, epbl_stable, ss, sf_stable, vd, DT, &
                             N_STEPS, mld_b, t_s, sample_every=N_STEPS/4)

         call check(error, mld_b(4) < 0.95_wp*mld_a(4), &
                    "stabilizing flux failed to shoal the MLD")
      end block checks
      call vd%destroy(); call sf_stable%destroy(); call sf_neutral%destroy()
      call ss%destroy(); call epbl_stable%destroy(); call epbl_neutral%destroy()
      call ms%destroy()
   end subroutine test_stable_shoals

   subroutine test_convective(error)
      !! Pure convection with the production ordering (cooling
      !! applied to T each step BEFORE EPBL): the deepening must
      !! track the encroachment scale D_enc = sqrt(2 |B0| t)/N.
      !! Discrete-layer + transition effects spread the result, so
      !! the band is generous; tighten during validation tuning.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 60
      real(wp), parameter :: DZ = 2.5_wp, DT = 1800.0_wp
      real(wp), parameter :: Q_HEAT = -200.0_wp
      real(wp), parameter :: N2 = 1.0e-4_wp
      integer, parameter :: N_STEPS = 96           ! 2 days
      integer, parameter :: N_SAMPLE = 8
      real(wp) :: mld_series(N_SAMPLE), t_series(N_SAMPLE)
      real(wp) :: dT_dz, q_t_kin, b0_mag, d_enc, ratio
      integer :: m, i_probe, j_probe
      logical :: monotone
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_epbl(epbl, grid, NZ)
         call ss%init(grid)
         call ss%set_wind_stress_const(0.0_wp, 0.0_wp)
         call sf%init(grid)
         call sf%set_surface_flux_const(Q_HEAT, 0.0_wp)
         call vd%init(grid, nz_ml=NZ)
         dT_dz = N2*RHO0/(GRAVITY*ALPHA_LIN)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)

         call run_epbl_steps(grid, ms, epbl, ss, sf, vd, DT, N_STEPS, &
                             mld_series, t_series, sample_every=N_STEPS/N_SAMPLE)

         monotone = .true.
         do m = 2, N_SAMPLE
            if (mld_series(m) < mld_series(m - 1) - 1.0e-9_wp) monotone = .false.
         end do
         call check(error, monotone, "convective MLD must grow monotonically")
         if (allocated(error)) exit checks

         q_t_kin = Q_HEAT/(RHO0*SEAWATER_CP)
         b0_mag = abs(GRAVITY*ALPHA_LIN*q_t_kin/RHO0)
         d_enc = sqrt(2.0_wp*b0_mag*t_series(N_SAMPLE))/sqrt(N2)
         ratio = mld_series(N_SAMPLE)/d_enc
         call check(error, ratio > 0.5_wp .and. ratio < 1.4_wp, &
                    "convective MLD outside [0.5, 1.4] of encroachment")
         if (allocated(error)) exit checks

         ! Diffusivity must be active inside the convective layer.
         i_probe = grid%nx_total/2
         j_probe = grid%ny_total/2
         call check(error, epbl%kd_int(i_probe, j_probe, NZ) > 1.0e-6_wp, &
                    "no convective diffusivity at the near-surface interface")
      end block checks
      call vd%destroy(); call sf%destroy(); call ss%destroy()
      call epbl%destroy(); call ms%destroy()
   end subroutine test_convective

   ! -----------------------------------------------------------------
   ! Langmuir (LF17 wind-only path)
   ! -----------------------------------------------------------------

   subroutine test_lf17_spot(error)
      !! La spot values vs the Python reference implementation
      !! (post floor-removal): the COARE 3.5
      !! u*->U10 inversion + Phillips-spectrum SL-averaged Stokes
      !! drift, zsl = 0.04*BLD, raw La = sqrt(u*/u_s_SL).
      type(error_type), allocatable, intent(out) :: error
      real(wp), parameter :: USTAR_REF(4) = [0.005_wp, 0.01_wp, 0.01_wp, 0.02_wp]
      real(wp), parameter :: BLD_REF(4) = [20.0_wp, 20.0_wp, 50.0_wp, 50.0_wp]
      real(wp), parameter :: LA_REF(4) = [0.4129_wp, 0.3627_wp, 0.4372_wp, 0.3947_wp]
      real(wp), parameter :: U10_REF(4) = [5.08_wp, 8.51_wp, 8.51_wp, 14.01_wp]
      real(wp) :: u10, ustokes, kphil, la
      integer :: n
      checks: block
         do n = 1, 4
            call epbl_lf17_wave_state(USTAR_REF(n), RHO0, u10, ustokes, kphil)
            call check(error, abs(u10 - U10_REF(n)) < 0.02_wp*U10_REF(n), &
                       "LF17 U10 outside 2% of the prototype reference")
            if (allocated(error)) exit checks
            la = epbl_lf17_la(USTAR_REF(n), 0.04_wp*BLD_REF(n), ustokes, kphil)
            call check(error, abs(la - LA_REF(n)) < 0.01_wp*LA_REF(n), &
                       "LF17 La outside 1% of the prototype reference")
            if (allocated(error)) exit checks
         end do
      end block checks
   end subroutine test_lf17_spot

   subroutine test_lt_monotone(error)
      !! With the stability modification off (lac = 0): smaller La =>
      !! larger multiplicative enhancement, capped at lt_max_enhance.
      type(error_type), allocatable, intent(out) :: error
      real(wp) :: m_hi_la, m_lo_la, m_tiny_la
      checks: block
         m_hi_la = 1.0_wp
         call epbl_lt_enhance(EPBL_LT_RESCALE, 0.447_wp, -1.33_wp, 5.0_wp, &
                              0.41_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
                              0.6_wp, 0.0_wp, 0.01_wp, 50.0_wp, 0.0_wp, m_hi_la)
         m_lo_la = 1.0_wp
         call epbl_lt_enhance(EPBL_LT_RESCALE, 0.447_wp, -1.33_wp, 5.0_wp, &
                              0.41_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
                              0.3_wp, 0.0_wp, 0.01_wp, 50.0_wp, 0.0_wp, m_lo_la)
         m_tiny_la = 1.0_wp
         call epbl_lt_enhance(EPBL_LT_RESCALE, 0.447_wp, -1.33_wp, 5.0_wp, &
                              0.41_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
                              0.01_wp, 0.0_wp, 0.01_wp, 50.0_wp, 0.0_wp, m_tiny_la)
         call check(error, m_hi_la > 1.0_wp, "LT must enhance mstar (La = 0.6)")
         if (allocated(error)) exit checks
         call check(error, m_lo_la > m_hi_la, &
                    "smaller La must enhance more (La 0.3 vs 0.6)")
         if (allocated(error)) exit checks
         call check(error, abs(m_tiny_la - 5.0_wp) < 1.0e-12_wp, &
                    "enhancement must cap at lt_max_enhance for tiny La")
         if (allocated(error)) exit checks
         ! Hand value: 1 + 0.447*0.3^(-1.33) = 1 + 0.447*exp(-1.33*log(0.3)).
         call check(error, abs(m_lo_la - (1.0_wp + 0.447_wp*0.3_wp**(-1.33_wp))) &
                    < 1.0e-12_wp, "rescale formula mismatch at La = 0.3")
      end block checks
   end subroutine test_lt_monotone

   subroutine test_lt_deepens(error)
      !! End-to-end: same wind-deepening setup, LT off vs LT on (lac
      !! = 0, rescale).  The Langmuir enhancement multiplies mstar by
      !! ~3x at La ~ 0.36, so the LT-on MLD must be clearly deeper.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_epbl_t) :: epbl_off, epbl_on
      type(ocean_surface_stress_t) :: ss
      type(ocean_surface_flux_t) :: sf
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 80
      real(wp), parameter :: DZ = 3.0_wp, DT = 1800.0_wp
      integer, parameter :: N_STEPS = 48           ! 1 day
      real(wp) :: mld_a(4), mld_b(4), t_s(4), dT_dz
      checks: block
         call make_grid(grid, 6, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call ss%init(grid)
         call ss%set_wind_stress_const(RHO0*0.01_wp**2, 0.0_wp)
         call sf%init(grid)
         call vd%init(grid, nz_ml=NZ)
         dT_dz = 1.0e-4_wp*RHO0/(GRAVITY*ALPHA_LIN)

         call setup_epbl(epbl_off, grid, NZ)
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)
         call run_epbl_steps(grid, ms, epbl_off, ss, sf, vd, DT, N_STEPS, &
                             mld_a, t_s, sample_every=N_STEPS/4)

         call setup_epbl(epbl_on, grid, NZ)
         epbl_on%use_lt = .true.
         epbl_on%lt_scheme = EPBL_LT_RESCALE
         epbl_on%lt_lac1 = 0.0_wp
         epbl_on%lt_lac4 = 0.0_wp
         epbl_on%lt_lac5 = 0.0_wp
         call setup_stratified_T(ms, NZ, DZ, 15.0_wp, dT_dz)
         call run_epbl_steps(grid, ms, epbl_on, ss, sf, vd, DT, N_STEPS, &
                             mld_b, t_s, sample_every=N_STEPS/4)

         call check(error, mld_b(4) > 1.1_wp*mld_a(4), &
                    "Langmuir enhancement failed to deepen the wind-mixed layer")
         if (allocated(error)) exit checks
         ! La diagnostic populated and in the wind-sea range.
         call check(error, epbl_on%la(grid%nx_total/2, grid%ny_total/2) > 0.2_wp &
                    .and. epbl_on%la(grid%nx_total/2, grid%ny_total/2) < 0.6_wp, &
                    "La diagnostic outside the wind-sea range")
         if (allocated(error)) exit checks
         call check(error, abs(epbl_off%la(grid%nx_total/2, grid%ny_total/2)) &
                    < 1.0e-30_wp, "La must stay 0 with use_lt off")
      end block checks
      call vd%destroy(); call sf%destroy(); call ss%destroy()
      call epbl_on%destroy(); call epbl_off%destroy(); call ms%destroy()
   end subroutine test_lt_deepens

end module test_ocean_epbl
