!! Unit and analytical tests for the kappa-shear interior closure
!! (`rdb_ocean_kappa_shear`).  Golden values generated by a Python
!! reference prototype of the JHL08 column solve.
!!
!! Global index convention (Roundabout bottom-up):
!!   kd_int(:,:,K=1) = bed (always 0)
!!   kd_int(:,:,K=nz+1) = surface (always 0)
!! Local prototype surface-down: K_local=0 surface, K_local=nz bed.
!! Flip: global K = nz+2 - K_local.
module test_ocean_kappa_shear
   use testdrive, only: new_unittest, unittest_type, error_type, check
   use rdb_constants, only: wp, GRAVITY, NZ_STACK_MAX
   use rdb_grid, only: hgrid_t
   use rdb_multilayer_state, only: multilayer_state_t
   use rdb_ocean_kappa_shear, only: ocean_kappa_shear_t, &
                                    kappa_shear_compute, &
                                    kappa_shear_merge_into_kv_kt, &
                                    kappa_shear_vertex_scatter, &
                                    ks_gather_corner
   use rdb_ocean_vdiff, only: ocean_vdiff_t, vdiff_apply_momentum
   use rdb_eos, only: EOS_VARIANT_LINEAR
   implicit none
   private

   public :: collect_ocean_kappa_shear_tests

   integer, parameter :: NGHOST = 2
   real(wp), parameter :: RHO0_KS = 1025.0_wp
   !! Thermal expansion in kg/m³/K (Fortran EOS convention).
   !! The prototype uses alpha_T=2e-4 in 1/K (dimensionless), so the Fortran
   !! slot value must be RHO0 * 2e-4 = 0.205 so that:
   !!   dbuoy_t = G * alpha_lin / rho0 = G * 2e-4   (matches prototype G*ALPHA_T)
   real(wp), parameter :: ALPHA_LIN_KS = RHO0_KS*2.0e-4_wp  ! 0.205 kg/m³/K
   real(wp), parameter :: BETA_LIN_KS = RHO0_KS*7.6e-4_wp  ! matches prototype
   real(wp), parameter :: F_CORIOLIS = 1.0e-4_wp
   !! Use the SAME gravity the kernel's buoyancy derivatives use
   !! (rdb_constants GRAVITY) so the column construction and the kernel
   !! agree exactly — the prototype is run with G=GRAVITY to match.
   real(wp), parameter :: GRAVITY_KS = GRAVITY

contains

   subroutine collect_ocean_kappa_shear_tests(testsuite)
      type(unittest_type), allocatable, intent(out) :: testsuite(:)

      testsuite = [ &
                  new_unittest("kshear_no_source", test_no_source), &
                  new_unittest("kshear_activation", test_activation), &
                  new_unittest("kshear_golden_profile", test_golden_profile), &
                  new_unittest("kshear_self_limiting", test_self_limiting), &
                  new_unittest("kshear_merge_arm", test_merge), &
                  new_unittest("kshear_vertex_eq_column", test_vertex_eq_column), &
                  new_unittest("kshear_vertex_isolated_wet_cell", &
                               test_vertex_isolated_wet_cell), &
                  new_unittest("kshear_vertex_partial_corner_gather", &
                               test_vertex_partial_corner_gather), &
                  new_unittest("kshear_vertex_scatter_modes", &
                               test_vertex_scatter_modes), &
                  new_unittest("kshear_vertex_device_resident", &
                               test_vertex_device_resident), &
                  new_unittest("kshear_vertex_kv_merge_skips_kv", &
                               test_vertex_kv_merge_skips_kv), &
                  new_unittest("kshear_vertex_kv_face_locality", &
                               test_vertex_kv_face_locality), &
                  new_unittest("kshear_vertex_kv_corner_vs_centre", &
                               test_vertex_kv_corner_vs_centre), &
                  new_unittest("kshear_vertex_kv_device_resident", &
                               test_vertex_kv_device_resident) &
                  ]
   end subroutine collect_ocean_kappa_shear_tests

   ! ------------------------------------------------------------------
   ! Helpers
   ! ------------------------------------------------------------------

   subroutine make_grid(grid, nx_phys, ny_phys)
      type(hgrid_t), intent(out) :: grid
      integer, intent(in) :: nx_phys, ny_phys
      call grid%init(nx_phys, ny_phys, NGHOST, 1.0_wp, 1.0_wp)
   end subroutine make_grid

   subroutine setup_ks(ks, grid, nz)
      !! Default kappa-shear configuration: linear EOS, f from F_CORIOLIS.
      type(ocean_kappa_shear_t), intent(inout) :: ks
      type(hgrid_t), intent(in) :: grid
      integer, intent(in) :: nz
      call ks%init(grid, nz_ml=nz)
      ks%enable = .true.
      ks%eos%variant = EOS_VARIANT_LINEAR
      ks%eos%alpha_T = ALPHA_LIN_KS
      ks%eos%beta_S = BETA_LIN_KS
      ks%eos%rho0 = RHO0_KS
      ks%rho0 = RHO0_KS
      call ks%set_f_centre(grid, F_CORIOLIS, 0.0_wp, 0.0_wp)
   end subroutine setup_ks

   !! Fill a multilayer_state with a stable stratified resting column.
   !! T decreases linearly from t_surf at k=nz (surface) downward.
   !! S is uniform.  u=v=0.
   subroutine setup_stable_column(ms, nz, dz, t_surf, dt_dz)
      type(multilayer_state_t), intent(inout) :: ms
      integer, intent(in) :: nz
      real(wp), intent(in) :: dz, t_surf, dt_dz
      integer :: k
      real(wp) :: z_below, t_k

      ms%h_layer = dz
      ms%u_face_x_layer = 0.0_wp
      ms%v_face_y_layer = 0.0_wp
      do k = 1, nz
         ! bottom-up: k=nz is surface, k=1 is bed
         z_below = real(nz - k, wp)*dz + 0.5_wp*dz
         t_k = t_surf - dt_dz*z_below
         ms%tracers(ms%idx_temperature)%hTr(:, :, k) = t_k*dz
         ms%tracers(ms%idx_salinity)%hTr(:, :, k) = 35.0_wp*dz
      end do
   end subroutine setup_stable_column

   !! Fill a multilayer_state with a tanh shear profile (surface-down
   !! physically), mapped to the global bottom-up layer order.
   !! T has a weak stable stratification (strat_N2), S uniform, v=0.
   !! u_face_x and v_face_y are set so both C-grid faces of a cell carry the
   !! same value, so the face-averaged centre velocity equals u_profile.
   subroutine setup_shear_column(ms, nz, dz, du, shear_depth_m, shear_width_m, strat_N2)
      type(multilayer_state_t), intent(inout) :: ms
      integer, intent(in) :: nz
      real(wp), intent(in) :: dz, du, shear_depth_m, shear_width_m, strat_N2
      integer :: k
      real(wp) :: z_sd, t_k, u_k, dt_per_m

      ! Prototype: dT_per_m = N2/(G*alpha_T_dimless) = N2/(G*(alpha_lin/rho0))
      dt_per_m = strat_N2*RHO0_KS/(GRAVITY_KS*ALPHA_LIN_KS)
      ms%h_layer = dz
      ms%u_face_x_layer = 0.0_wp
      ms%v_face_y_layer = 0.0_wp

      do k = 1, nz
         ! local surface-down index: k_sd = nz+1-k (k_sd=1 surface)
         ! z_sd = depth of layer-centre below surface (surface-down)
         z_sd = (real(nz - k, wp) + 0.5_wp)*dz
         t_k = 20.0_wp - dt_per_m*z_sd
         u_k = du*tanh((shear_depth_m - z_sd)/shear_width_m)

         ms%tracers(ms%idx_temperature)%hTr(:, :, k) = t_k*dz
         ms%tracers(ms%idx_salinity)%hTr(:, :, k) = 35.0_wp*dz
         ! Both faces equal u_k -> face-average = u_k
         ms%u_face_x_layer(:, :, k) = u_k
      end do
   end subroutine setup_shear_column

   ! ------------------------------------------------------------------
   ! Test 1: no_source — stable resting column
   ! ------------------------------------------------------------------

   subroutine test_no_source(error)
      !! Strongly stratified resting column (T decreasing 0.05 K/m, no shear).
      !! After kappa_shear_compute: kd_int == 0 exactly everywhere;
      !! tke_int should be near TKE_min = 1e-20 at interior interfaces.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 20
      real(wp), parameter :: DZ = 10.0_wp, DT = 1800.0_wp
      integer :: i, j, k
      real(wp) :: kd_max, tke_max_interior
      checks: block
         call make_grid(grid, 4, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         call setup_stable_column(ms, NZ, DZ, 20.0_wp, 0.05_wp)

         call kappa_shear_compute(grid, ks, ms, DT)

         ! kd_int must be exactly 0 everywhere
         kd_max = 0.0_wp
         do k = 1, NZ + 1
            do j = 1, grid%ny_total
               do i = 1, grid%nx_total
                  if (abs(ks%kd_int(i, j, k)) > kd_max) &
                     kd_max = abs(ks%kd_int(i, j, k))
               end do
            end do
         end do
         call check(error, kd_max == 0.0_wp, &
                    "no-source column: kd_int must be identically 0")
         if (allocated(error)) exit checks

         ! Bed and surface interfaces must be exactly 0
         call check(error, abs(ks%kd_int(1, 1, 1)) == 0.0_wp, &
                    "bed interface kd_int must be 0")
         if (allocated(error)) exit checks
         call check(error, abs(ks%kd_int(1, 1, NZ + 1)) == 0.0_wp, &
                    "surface interface kd_int must be 0")
         if (allocated(error)) exit checks

         ! tke_int at interior interfaces should be very small (TKE_min = 1e-20)
         tke_max_interior = 0.0_wp
         do k = 2, NZ
            tke_max_interior = max(tke_max_interior, abs(ks%tke_int(1, 1, k)))
         end do
         call check(error, tke_max_interior < 1.0e-15_wp, &
                    "no-source column: interior tke_int should be near TKE_min")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_no_source

   ! ------------------------------------------------------------------
   ! Test 2: activation — shear layer drives kd_int > 0
   ! ------------------------------------------------------------------

   subroutine test_activation(error)
      !! Tanh shear profile centred at mid-column with Ri_min ~ 0.1 < 0.25.
      !! Structural assertions (no exact values):
      !!   * kd_int > 0 somewhere in the interior
      !!   * kd_int(:,:,1) == 0 exactly (bed)
      !!   * kd_int(:,:,nz+1) == 0 exactly (surface)
      !!   * profile has a single interior maximum (single-signed, interior-peaked)
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 40
      real(wp), parameter :: DZ = 5.0_wp, DT = 1800.0_wp
      integer :: i_probe, j_probe, k, k_max
      real(wp) :: kd_max, kd_k
      logical :: all_nonneg
      checks: block
         call make_grid(grid, 4, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         ! shear centred at depth 100 m (mid of 200 m column)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 100.0_wp, 20.0_wp, 3.0e-5_wp)

         call kappa_shear_compute(grid, ks, ms, DT)

         i_probe = grid%nx_total/2
         j_probe = grid%ny_total/2

         ! Bed and surface interfaces must be exactly 0
         call check(error, ks%kd_int(i_probe, j_probe, 1) == 0.0_wp, &
                    "activation: bed interface kd_int must be 0")
         if (allocated(error)) exit checks
         call check(error, ks%kd_int(i_probe, j_probe, NZ + 1) == 0.0_wp, &
                    "activation: surface interface kd_int must be 0")
         if (allocated(error)) exit checks

         ! Some interior value > 0
         kd_max = 0.0_wp
         k_max = 0
         do k = 2, NZ
            kd_k = ks%kd_int(i_probe, j_probe, k)
            if (kd_k > kd_max) then
               kd_max = kd_k
               k_max = k
            end if
         end do
         call check(error, kd_max > 0.0_wp, &
                    "activation: kd_int must be > 0 somewhere interior")
         if (allocated(error)) exit checks

         ! All interior values non-negative
         all_nonneg = .true.
         do k = 2, NZ
            if (ks%kd_int(i_probe, j_probe, k) < 0.0_wp) all_nonneg = .false.
         end do
         call check(error, all_nonneg, &
                    "activation: kd_int must be non-negative everywhere")
         if (allocated(error)) exit checks

         ! Peak must be interior (not at K=2 or K=NZ)
         call check(error, k_max > 2 .and. k_max < NZ, &
                    "activation: kd_int max must be in the interior, not at boundary")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_activation

   ! ------------------------------------------------------------------
   ! Test 3: golden_profile — exact match to prototype
   ! ------------------------------------------------------------------

   subroutine test_golden_profile(error)
      !! Exactly the same column as the prototype --golden output:
      !!   nz=20, h=5m, du=0.5, strat_N2=3e-5, shear_width=20m
      !!   linear EOS (ALPHA_T=2e-4, BETA_S=7.6e-4, RHO0=1025)
      !!   f=1e-4 rad/s, dt=1800 s, all JHL08 default knobs.
      !!
      !! Golden kappa_avg values are PROTOTYPE-derived — generated by the
      !! Python reference prototype with GRAVITY set to rdb_constants GRAVITY (9.80665)
      !! so the column construction and the kernel buoyancy use the same g:
      !!
      !!   python3 -c "import sys; sys.path.insert(0,'tools'); \
      !!     import kappa_shear_prototype as ks; ks.G=9.80665; import numpy as np; \
      !!     h,u,v,T,S=ks._make_shear_column(nz=20,h_each=5.0,du=0.5, \
      !!       strat_N2=3e-5,shear_width_m=20.0); \
      !!     ka,*_=ks.kappa_shear_column(h,u,v,T,S,f2=1e-8,dt=1800.0,p=ks.Params()); \
      !!     [print(f'{x:.17e}') for x in ka]"
      !!
      !! Profile is symmetric, interior-peaked, nonzero at every interior
      !! interface (incl. the near-bed K_local=19).  The kernel matches the
      !! prototype to ~1e-13 relative; tolerance 1e-6 covers serial-arithmetic
      !! reorderings.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 20
      real(wp), parameter :: DZ = 5.0_wp, DT = 1800.0_wp
      real(wp), parameter :: TOL_REL = 1.0e-6_wp

      ! Golden kappa_avg from the Python prototype (surface-down local:
      ! K_local=0 surface = K_global=NZ+1, K_local=NZ bed = K_global=1).
      ! Fortran 1-based: golden_sd(1) = K_local=0, golden_sd(NZ+1) = K_local=NZ.
      real(wp), parameter :: GOLDEN_SD(NZ + 1) = [ &
                             0.00000000000000000e+00_wp, &  ! K_local=0  (surface, K_global=NZ+1)
                             5.84500291421640155e-03_wp, &  ! K_local=1
                             2.55834506759574087e-02_wp, &  ! K_local=2
                             6.18743388406512718e-02_wp, &  ! K_local=3
                             1.18040171371964375e-01_wp, &  ! K_local=4
                             1.94158207598627230e-01_wp, &  ! K_local=5
                             2.79264861473862980e-01_wp, &  ! K_local=6
                             3.75428011380740556e-01_wp, &  ! K_local=7
                             4.54336837449636988e-01_wp, &  ! K_local=8
                             5.06855656580426306e-01_wp, &  ! K_local=9
                             5.25366868234401263e-01_wp, &  ! K_local=10 (interior max)
                             5.06855484093826858e-01_wp, &  ! K_local=11
                             4.54336485854091421e-01_wp, &  ! K_local=12
                             3.75427466061297621e-01_wp, &  ! K_local=13
                             2.79264096140142026e-01_wp, &  ! K_local=14
                             1.94157172096779573e-01_wp, &  ! K_local=15
                             1.18038778175938969e-01_wp, &  ! K_local=16
                             6.18736389220278515e-02_wp, &  ! K_local=17
                             2.55832135500080882e-02_wp, &  ! K_local=18
                             5.84500603701821296e-03_wp, &  ! K_local=19  (near bed, nonzero)
                             0.00000000000000000e+00_wp &  ! K_local=20 (bed, K_global=1)
                             ]
      integer :: k_local, k_global
      real(wp) :: kd_fort, kd_ref, rel_err, max_rel_err
      character(len=80) :: msg
      integer :: i_probe, j_probe
      checks: block
         call make_grid(grid, 4, 4)
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         ! Exact prototype column: _make_shear_column(nz=20, h_each=5.0, du=0.5,
         !   strat_N2=3e-5, shear_width_m=20.0)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 50.0_wp, 20.0_wp, 3.0e-5_wp)

         call kappa_shear_compute(grid, ks, ms, DT)

         i_probe = grid%nx_total/2
         j_probe = grid%ny_total/2

         ! Check exact 0 at bed and surface
         call check(error, ks%kd_int(i_probe, j_probe, 1) == 0.0_wp, &
                    "golden: bed interface must be exactly 0")
         if (allocated(error)) exit checks
         call check(error, ks%kd_int(i_probe, j_probe, NZ + 1) == 0.0_wp, &
                    "golden: surface interface must be exactly 0")
         if (allocated(error)) exit checks

         ! Interface-by-interface comparison
         ! Index flip: local K_local=0 (surface) -> global K=NZ+1
         !             local K_local=NZ (bed)     -> global K=1
         ! k_global = NZ + 1 - k_local
         max_rel_err = 0.0_wp
         do k_local = 0, NZ
            k_global = NZ + 1 - k_local
            kd_fort = ks%kd_int(i_probe, j_probe, k_global)
            kd_ref = GOLDEN_SD(k_local + 1)
            if (kd_ref > 1.0e-10_wp) then
               rel_err = abs(kd_fort - kd_ref)/kd_ref
               if (rel_err > max_rel_err) max_rel_err = rel_err
               if (rel_err > TOL_REL) then
                  write (msg, '(a,i0,a,es13.6,a,es13.6,a,es9.2)') &
                     "golden K_local=", k_local, &
                     " fort=", kd_fort, " ref=", kd_ref, " rel=", rel_err
                  call check(error, .false., trim(msg))
                  exit checks
               end if
            end if
         end do
         call check(error, max_rel_err < TOL_REL, &
                    "golden profile: max relative error exceeds tolerance")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_golden_profile

   ! ------------------------------------------------------------------
   ! Test 4: self_limiting — second call gives much weaker mixing
   ! ------------------------------------------------------------------

   subroutine test_self_limiting(error)
      !! Run kappa_shear_compute on the activation column once to get
      !! kd_int. Then relax u,v 80% toward their column means (crude
      !! momentum blending to simulate mixing), recompute, and verify
      !! that max kd_int drops by > 5x.
      !! This exercises the self-limiting property of JHL08.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 40
      real(wp), parameter :: DZ = 5.0_wp, DT = 1800.0_wp
      integer :: k
      real(wp) :: kd_max1, kd_max2
      real(wp) :: u_mean, u_k
      integer :: i_probe, j_probe, nx, ny
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 100.0_wp, 20.0_wp, 3.0e-5_wp)

         call kappa_shear_compute(grid, ks, ms, DT)

         i_probe = nx/2
         j_probe = ny/2
         kd_max1 = 0.0_wp
         do k = 2, NZ
            if (ks%kd_int(i_probe, j_probe, k) > kd_max1) &
               kd_max1 = ks%kd_int(i_probe, j_probe, k)
         end do
         call check(error, kd_max1 > 0.0_wp, &
                    "self-limiting: first call must produce mixing")
         if (allocated(error)) exit checks

         ! Relax u,v 80% toward column mean: crude mixing proxy.
         ! This strongly reduces the vertical shear without perfectly eliminating it.
         u_mean = 0.0_wp
         do k = 1, NZ
            u_mean = u_mean + ms%u_face_x_layer(i_probe, j_probe, k)
         end do
         u_mean = u_mean/real(NZ, wp)
         do k = 1, NZ
            u_k = ms%u_face_x_layer(i_probe, j_probe, k)
            ms%u_face_x_layer(:, :, k) = u_mean + 0.2_wp*(u_k - u_mean)
         end do
         ! Also relax hTr for T
         do k = 1, NZ
            ms%tracers(ms%idx_temperature)%hTr(:, :, k) = &
               ms%tracers(ms%idx_temperature)%hTr(:, :, k)
         end do

         call kappa_shear_compute(grid, ks, ms, DT)

         kd_max2 = 0.0_wp
         do k = 2, NZ
            if (ks%kd_int(i_probe, j_probe, k) > kd_max2) &
               kd_max2 = ks%kd_int(i_probe, j_probe, k)
         end do

         call check(error, kd_max2 < kd_max1/5.0_wp, &
                    "self-limiting: max kd_int must drop > 5x after shear reduction")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_self_limiting

   ! ------------------------------------------------------------------
   ! Test 5: merge arm
   ! ------------------------------------------------------------------

   subroutine test_merge(error)
      !! Fill kd_int with a known pattern; fill kv/kt with a base value.
      !! Call kappa_shear_merge_into_kv_kt with prandtl_turb=0.8.
      !! Assert:
      !!   * kt(i,j,K) incremented by kd_int(i,j,K) for K=2..NZ (interior)
      !!   * kv(i,j,K) incremented by 0.8*kd_int(i,j,K) for K=2..NZ
      !!   * K=1 (bed) and K=NZ+1 (surface) untouched in kt and kv
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 6
      real(wp), parameter :: KV_BASE = 1.0e-4_wp
      real(wp), parameter :: KT_BASE = 5.0e-5_wp
      real(wp), parameter :: PR = 0.8_wp
      real(wp), allocatable :: kv(:, :, :), kt(:, :, :)
      integer :: i, j, k, nx, ny
      real(wp) :: kd_ref, expected_kt, expected_kv
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         call ks%init(grid, nz_ml=NZ)
         ks%prandtl_turb = PR

         ! Fill kd_int with a deterministic pattern: 0 at K=1,NZ+1; else K*1e-3
         do k = 1, NZ + 1
            ks%kd_int(:, :, k) = 0.0_wp
         end do
         do k = 2, NZ
            ks%kd_int(:, :, k) = real(k, wp)*1.0e-3_wp
         end do

         allocate (kv(nx, ny, NZ + 1), source=KV_BASE)
         allocate (kt(nx, ny, NZ + 1), source=KT_BASE)

         call kappa_shear_merge_into_kv_kt(ks, size(kt, 1), size(kt, 2), size(kt, 3), kv, kt)

         ! Bed (K=1) and surface (K=NZ+1) must be untouched
         call check(error, abs(kt(1, 1, 1) - KT_BASE) < 1.0e-30_wp, &
                    "merge: bed kt must be unchanged")
         if (allocated(error)) exit checks
         call check(error, abs(kv(1, 1, 1) - KV_BASE) < 1.0e-30_wp, &
                    "merge: bed kv must be unchanged")
         if (allocated(error)) exit checks
         call check(error, abs(kt(1, 1, NZ + 1) - KT_BASE) < 1.0e-30_wp, &
                    "merge: surface kt must be unchanged")
         if (allocated(error)) exit checks
         call check(error, abs(kv(1, 1, NZ + 1) - KV_BASE) < 1.0e-30_wp, &
                    "merge: surface kv must be unchanged")
         if (allocated(error)) exit checks

         ! Interior interfaces: kt = KT_BASE + kd_int, kv = KV_BASE + PR*kd_int
         do k = 2, NZ
            kd_ref = real(k, wp)*1.0e-3_wp
            expected_kt = KT_BASE + kd_ref
            expected_kv = KV_BASE + PR*kd_ref
            do j = 1, ny
               do i = 1, nx
                  call check(error, abs(kt(i, j, k) - expected_kt) < 1.0e-15_wp, &
                             "merge: kt incorrect at interior interface")
                  if (allocated(error)) exit checks
                  call check(error, abs(kv(i, j, k) - expected_kv) < 1.0e-15_wp, &
                             "merge: kv incorrect at interior interface")
                  if (allocated(error)) exit checks
               end do
            end do
         end do
      end block checks
      if (allocated(kv)) deallocate (kv)
      if (allocated(kt)) deallocate (kt)
      call ks%destroy()
   end subroutine test_merge

   ! ------------------------------------------------------------------
   ! Vertex-form helpers
   ! ------------------------------------------------------------------

   subroutine setup_vertex(ks, grid, nz)
      !! Arm the vertex form on an already-setup_ks'd slot: allocate the
      !! corner fields and fill SIGNED f at corners (f-plane, so the
      !! corner f^2 equals the centre f^2 bitwise — the vertex/column
      !! agreement tests REQUIRE beta = 0).
      type(ocean_kappa_shear_t), intent(inout) :: ks
      type(hgrid_t), intent(in) :: grid
      integer, intent(in) :: nz
      call ks%init_vertex(grid, nz)
      call ks%set_f_corner(grid, F_CORIOLIS, 0.0_wp, 0.0_wp)
   end subroutine setup_vertex

   subroutine make_wet_masks(wet_t, wet_u, wet_v, nx, ny)
      !! Derive the face masks from a tracer wet mask exactly as the
      !! metrics slot does: a face is open iff BOTH adjacent cells are
      !! wet; outer-boundary faces closed.
      integer, intent(in) :: nx, ny
      real(wp), intent(in) :: wet_t(nx, ny)
      real(wp), intent(out) :: wet_u(nx + 1, ny), wet_v(nx, ny + 1)
      integer :: i, j
      wet_u = 0.0_wp
      wet_v = 0.0_wp
      do j = 1, ny
         do i = 2, nx
            wet_u(i, j) = wet_t(i - 1, j)*wet_t(i, j)
         end do
      end do
      do j = 2, ny
         do i = 1, nx
            wet_v(i, j) = wet_t(i, j - 1)*wet_t(i, j)
         end do
      end do
   end subroutine make_wet_masks

   ! ------------------------------------------------------------------
   ! Test 6: vertex == column on a horizontally uniform f-plane basin
   ! ------------------------------------------------------------------

   subroutine test_vertex_eq_column(error)
      !! All cells wet, f uniform (beta=0), a single shear/stratification
      !! profile replicated everywhere, DZ = 8 m (a power of two, so
      !! every gather round-trip — u*h/h, hT*4/(h*4), 0.25*4x — is EXACT
      !! in IEEE arithmetic).  The corner gather then feeds the shared
      !! solver bitwise-identical columns, and the arithmetic-mean
      !! scatter of four equal corners is the identity, so the vertex
      !! path must reproduce the column path BITWISE on owned cells.
      !! The geometric mean (kdmin=0) of four equal values is the value
      !! to sqrt/mul roundoff — checked at 1e-13 relative.
      !! Endpoints (bed/surface) must be exactly 0 in both modes.
      !!
      !! Caveat (spec §T1): this equivalence holds because the rdb
      !! port deliberately does NOT reproduce MOM6's caller-side
      !! full_convection pre-step asymmetry (vertex path only).  If that
      !! pre-step is ever added, this test must be re-derived.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 20
      real(wp), parameter :: DZ = 8.0_wp, DT = 1800.0_wp
      real(wp), parameter :: TOL_GEO = 1.0e-13_wp
      real(wp), allocatable :: kd_col(:, :, :)
      real(wp), allocatable :: wet_t(:, :), wet_u(:, :), wet_v(:, :)
      integer :: i, j, k, nx, ny, ng
      real(wp) :: diff_max, ref, geo_err
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         ng = grid%nghost
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         ! shear centred at depth 80 m (mid of the 160 m column)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 80.0_wp, 20.0_wp, 3.0e-5_wp)

         ! ---- Column reference ----
         call kappa_shear_compute(grid, ks, ms, DT)
         allocate (kd_col(nx, ny, NZ + 1))
         kd_col = ks%kd_int

         call check(error, maxval(kd_col) > 0.0_wp, &
                    "vertex_eq_column: column reference must produce mixing")
         if (allocated(error)) exit checks

         ! ---- Vertex, arithmetic mean (default) — bitwise ----
         call setup_vertex(ks, grid, NZ)
         allocate (wet_t(nx, ny), wet_u(nx + 1, ny), wet_v(nx, ny + 1))
         wet_t = 1.0_wp
         wet_u = 1.0_wp
         wet_v = 1.0_wp
         ks%kd_int = -1.0_wp   ! ensure the vertex path overwrites everything
         call kappa_shear_compute(grid, ks, ms, DT, wet_t, wet_u, wet_v)

         diff_max = 0.0_wp
         do k = 1, NZ + 1
            do j = ng + 1, ny - ng
               do i = ng + 1, nx - ng
                  diff_max = max(diff_max, abs(ks%kd_int(i, j, k) - kd_col(i, j, k)))
               end do
            end do
         end do
         call check(error, diff_max == 0.0_wp, &
                    "vertex arithmetic mean must equal the column path BITWISE "// &
                    "on a uniform f-plane basin (DZ = power of two)")
         if (allocated(error)) exit checks
         call check(error, ks%kd_int(ng + 1, ng + 1, 1) == 0.0_wp .and. &
                    ks%kd_int(ng + 1, ng + 1, NZ + 1) == 0.0_wp, &
                    "vertex: bed and surface interfaces must be exactly 0")
         if (allocated(error)) exit checks

         ! ---- Vertex, geometric mean (kdmin = 0) — near-identity ----
         ks%vertex_geometric_mean = .true.
         ks%vertex_geomean_kdmin = 0.0_wp
         call kappa_shear_compute(grid, ks, ms, DT, wet_t, wet_u, wet_v)
         geo_err = 0.0_wp
         do k = 2, NZ
            do j = ng + 1, ny - ng
               do i = ng + 1, nx - ng
                  ref = kd_col(i, j, k)
                  if (ref > 1.0e-10_wp) then
                     geo_err = max(geo_err, abs(ks%kd_int(i, j, k) - ref)/ref)
                  else
                     ! Tiny/zero reference: the geometric mean of four
                     ! equal tiny corners is that tiny value (0 stays
                     ! exactly 0) — bound the absolute deviation.
                     call check(error, abs(ks%kd_int(i, j, k) - ref) <= 1.0e-12_wp, &
                                "vertex geometric (kdmin=0): tiny/zero interfaces track the column")
                     if (allocated(error)) exit checks
                  end if
               end do
            end do
         end do
         call check(error, geo_err < TOL_GEO, &
                    "vertex geometric mean of four equal corners must be the "// &
                    "corner value to sqrt/mul roundoff")
         if (allocated(error)) exit checks
         call check(error, ks%kd_int(ng + 1, ng + 1, 1) == 0.0_wp .and. &
                    ks%kd_int(ng + 1, ng + 1, NZ + 1) == 0.0_wp, &
                    "vertex geometric: bed and surface interfaces must be exactly 0")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_vertex_eq_column

   ! ------------------------------------------------------------------
   ! Test 7: isolated wet cell — activity test, not the mask multiply
   ! ------------------------------------------------------------------

   subroutine test_vertex_isolated_wet_cell(error)
      !! One wet cell in a sea of land: all four of its velocity faces
      !! are closed, so all four of its corners fail the ANY-face-open
      !! activity test and are never solved — kd_int is exactly 0 at
      !! every interface of the wet cell even though its column carries
      !! strong shear (the column path on the same state produces
      !! kd > 0, proving the assertion has teeth).  Note this test alone
      !! is NOT a full staggering canary (a uniform shift leaves all
      !! corners inactive either way) — the hand-computed
      !! partially-wet-corner gather test is what pins the corner/cell
      !! index translation.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 20
      real(wp), parameter :: DZ = 8.0_wp, DT = 1800.0_wp
      integer, parameter :: IW = 4, JW = 4   ! the isolated wet cell
      real(wp), allocatable :: wet_t(:, :), wet_u(:, :), wet_v(:, :)
      integer :: nx, ny
      real(wp) :: kd_max
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 80.0_wp, 20.0_wp, 3.0e-5_wp)

         ! Teeth: the column path mixes at (IW,JW).
         call kappa_shear_compute(grid, ks, ms, DT)
         call check(error, maxval(ks%kd_int(IW, JW, :)) > 0.0_wp, &
                    "isolated-wet-cell: column path must mix (teeth check)")
         if (allocated(error)) exit checks

         call setup_vertex(ks, grid, NZ)
         allocate (wet_t(nx, ny), wet_u(nx + 1, ny), wet_v(nx, ny + 1))
         wet_t = 0.0_wp
         wet_t(IW, JW) = 1.0_wp
         call make_wet_masks(wet_t, wet_u, wet_v, nx, ny)
         ks%kd_int = -1.0_wp
         call kappa_shear_compute(grid, ks, ms, DT, wet_t, wet_u, wet_v)

         kd_max = maxval(abs(ks%kd_int))
         call check(error, kd_max == 0.0_wp, &
                    "isolated wet cell: kd_int must be exactly 0 everywhere "// &
                    "(all four corners fail the any-face-open activity test)")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_vertex_isolated_wet_cell

   ! ------------------------------------------------------------------
   ! Test 8: partially-wet corner gather — hand-computed mask algebra
   ! ------------------------------------------------------------------

   subroutine test_vertex_partial_corner_gather(error)
      !! Direct unit test of `ks_gather_corner` at a corner with three
      !! wet cells and one land cell (NE), all wet cells carrying
      !! DIFFERENT thicknesses.  Asserts, hand-computed:
      !!   * corner h = mean of the THREE wet thicknesses (not /4);
      !!   * corner T = thickness-weighted mean of the wet cells;
      !!   * corner u/v = the open transverse face's value alone (the
      !!     face into the land pair carries zero face-thickness);
      !!   * the land cell's h/T/u/v have NO influence — re-gather with
      !!     wildly different land values is bitwise identical;
      !!   * the surface-down flip: local k=1 reads global layer nz.
      !! This is the test that catches the MOM6-NE vs Roundabout-SW corner
      !! translation being off by one (a uniform field is
      !! shift-invariant; this one is not).
      type(error_type), allocatable, intent(out) :: error
      integer, parameter :: NXL = 6, NYL = 6, NZC = 3
      integer, parameter :: IC = 4, JC = 4
      real(wp) :: h_layer(NXL, NYL, NZC), hT(NXL, NYL, NZC), hS(NXL, NYL, NZC)
      real(wp) :: u_face(NXL + 1, NYL, NZC), v_face(NXL, NYL + 1, NZC)
      real(wp) :: wet_t(NXL, NYL), wet_u(NXL + 1, NYL), wet_v(NXL, NYL + 1)
      real(wp) :: h_sd(NZ_STACK_MAX), u_sd(NZ_STACK_MAX), v_sd(NZ_STACK_MAX)
      real(wp) :: t_sd(NZ_STACK_MAX), s_sd(NZ_STACK_MAX)
      real(wp) :: h_sd2(NZ_STACK_MAX), u_sd2(NZ_STACK_MAX), v_sd2(NZ_STACK_MAX)
      real(wp) :: t_sd2(NZ_STACK_MAX), s_sd2(NZ_STACK_MAX)
      real(wp), parameter :: TOL = 1.0e-14_wp
      real(wp) :: h_sw, t_exp, h_exp
      integer :: k, kg
      logical :: same
      checks: block
         ! Patch around corner (IC,JC): SW=(3,3), SE=(4,3), NW=(3,4),
         ! NE=(4,4).  NE is LAND; its fields are poison.
         wet_t = 1.0_wp
         wet_t(IC, JC) = 0.0_wp
         call make_wet_masks(wet_t, wet_u, wet_v, NXL, NYL)

         h_layer = 2.0_wp
         hT = 2.0_wp*10.0_wp       ! T=10 background
         hS = 2.0_wp*35.0_wp
         u_face = 0.0_wp
         v_face = 0.0_wp
         do kg = 1, NZC
            h_layer(3, 3, kg) = 4.0_wp*real(kg, wp)   ! SW: depth-dependent
            h_layer(4, 3, kg) = 8.0_wp                ! SE
            h_layer(3, 4, kg) = 12.0_wp               ! NW
            h_layer(4, 4, kg) = 64.0_wp               ! NE (land, poison)
            hT(3, 3, kg) = 2.0_wp*h_layer(3, 3, kg)   ! T_sw = 2
            hT(4, 3, kg) = 1.0_wp*8.0_wp              ! T_se = 1
            hT(3, 4, kg) = 1.0_wp*12.0_wp             ! T_nw = 1
            hT(4, 4, kg) = 7.0_wp*64.0_wp             ! T_ne = 7 (poison)
            ! Keep S = 35 in every WET patch cell (hS tracks the patched h).
            hS(3, 3, kg) = 35.0_wp*h_layer(3, 3, kg)
            hS(4, 3, kg) = 35.0_wp*8.0_wp
            hS(3, 4, kg) = 35.0_wp*12.0_wp
            hS(4, 4, kg) = 11.0_wp*64.0_wp            ! S_ne = 11 (poison)
         end do
         ! Faces: south u-face (into the wet SW/SE pair) carries 0.5;
         ! north u-face (NW/NE pair, closed by land) carries poison.
         u_face(IC, JC - 1, :) = 0.5_wp
         u_face(IC, JC, :) = 99.0_wp
         v_face(IC - 1, JC, :) = 0.25_wp
         v_face(IC, JC, :) = -77.0_wp

         call ks_gather_corner(NXL, NYL, NZC, IC, JC, h_layer, u_face, &
                               v_face, hT, hS, wet_t, wet_u, wet_v, &
                               h_sd, u_sd, v_sd, t_sd, s_sd)

         do k = 1, NZC
            kg = NZC + 1 - k     ! the flip under test
            h_sw = 4.0_wp*real(kg, wp)
            ! h: mean of the three WET thicknesses (mask weights).
            h_exp = (h_sw + 8.0_wp + 12.0_wp)/3.0_wp
            call check(error, abs(h_sd(k) - h_exp) <= TOL*h_exp, &
                       "partial corner: h must be the mean of the 3 wet cells")
            if (allocated(error)) exit checks
            ! T: thickness-weighted mean of the wet cells.
            t_exp = (2.0_wp*h_sw + 8.0_wp + 12.0_wp)/(h_sw + 20.0_wp)
            call check(error, abs(t_sd(k) - t_exp) <= TOL*t_exp, &
                       "partial corner: T must be the h-weighted wet-cell mean")
            if (allocated(error)) exit checks
            ! u: only the south face is open -> exactly its value.
            call check(error, u_sd(k) == 0.5_wp, &
                       "partial corner: u must be the open south face's value")
            if (allocated(error)) exit checks
            call check(error, v_sd(k) == 0.25_wp, &
                       "partial corner: v must be the open west face's value")
            if (allocated(error)) exit checks
            call check(error, abs(s_sd(k) - 35.0_wp) <= TOL*35.0_wp, &
                       "partial corner: uniform S must survive the gather")
            if (allocated(error)) exit checks
         end do

         ! Land-cell invariance: change every NE (land) input wildly;
         ! the gather must be BITWISE unchanged.
         h_layer(4, 4, :) = 1.0e6_wp
         hT(4, 4, :) = -3.0e7_wp
         hS(4, 4, :) = 5.0e5_wp
         u_face(IC, JC, :) = -1.0e4_wp
         v_face(IC, JC, :) = 2.0e4_wp
         call ks_gather_corner(NXL, NYL, NZC, IC, JC, h_layer, u_face, &
                               v_face, hT, hS, wet_t, wet_u, wet_v, &
                               h_sd2, u_sd2, v_sd2, t_sd2, s_sd2)
         same = .true.
         do k = 1, NZC
            if (h_sd2(k) /= h_sd(k) .or. u_sd2(k) /= u_sd(k) .or. &
                v_sd2(k) /= v_sd(k) .or. t_sd2(k) /= t_sd(k) .or. &
                s_sd2(k) /= s_sd(k)) same = .false.
         end do
         call check(error, same, &
                    "partial corner: the land cell's values must have "// &
                    "exactly zero influence on the gather")
      end block checks
   end subroutine test_vertex_partial_corner_gather

   ! ------------------------------------------------------------------
   ! Test 9: scatter averaging-mode algebra on synthetic corner data
   ! ------------------------------------------------------------------

   subroutine test_vertex_scatter_modes(error)
      !! Unit test of `kappa_shear_vertex_scatter` (Pass C) alone, on a
      !! hand-written corner field: four equal corners are the identity
      !! in both modes; AM >= GM pointwise; a single zero corner with
      !! kdmin=0 hard-zeros the geometric mean (bitwise 0); kdmin=1e-9
      !! floors it to the hand-computed 4th root; a land tracer cell is
      !! 0 regardless of its corners; endpoints exactly 0; tke zeroed.
      type(error_type), allocatable, intent(out) :: error
      integer, parameter :: NXL = 4, NYL = 4, NZP1 = 4
      real(wp) :: kd_corner(NXL + 1, NYL + 1, NZP1)
      real(wp) :: kd_int(NXL, NYL, NZP1), tke_int(NXL, NYL, NZP1)
      real(wp) :: wet_t(NXL, NYL)
      real(wp), parameter :: A = 1.0e-3_wp, B = 2.0e-3_wp
      real(wp), parameter :: C = 3.0e-3_wp, D = 4.0e-3_wp
      real(wp), parameter :: KDMIN = 1.0e-9_wp
      real(wp), parameter :: TOL = 1.0e-15_wp
      real(wp) :: am, gm, expect
      integer :: k
      checks: block
         wet_t = 1.0_wp
         wet_t(3, 3) = 0.0_wp    ! a land cell with live corners
         kd_corner = 5.0e-4_wp   ! background: four equal corners
         ! Cell (2,2)'s corners: SW=(2,2)=A, SE=(3,2)=B, NW=(2,3)=C, NE=(3,3)=D.
         kd_corner(2, 2, 2) = A
         kd_corner(3, 2, 2) = B
         kd_corner(2, 3, 2) = C
         kd_corner(3, 3, 2) = D

         ! ---- Arithmetic mode ----
         call kappa_shear_vertex_scatter(NXL, NYL, NZP1, .false., 0.0_wp, &
                                         wet_t, kd_corner, kd_int, tke_int)
         am = 0.25_wp*((A + D) + (C + B))
         call check(error, abs(kd_int(2, 2, 2) - am) <= TOL, &
                    "scatter arithmetic: 0.25*((SW+NE)+(NW+SE))")
         if (allocated(error)) exit checks
         call check(error, kd_int(4, 4, 2) == 5.0e-4_wp, &
                    "scatter arithmetic: four equal corners are the identity")
         if (allocated(error)) exit checks
         call check(error, kd_int(3, 3, 2) == 0.0_wp, &
                    "scatter: land tracer cell must be exactly 0")
         if (allocated(error)) exit checks
         do k = 1, NZP1, NZP1 - 1   ! k = 1 and k = NZP1
            call check(error, maxval(abs(kd_int(:, :, k))) == 0.0_wp, &
                       "scatter: bed/surface endpoints must be exactly 0")
            if (allocated(error)) exit checks
         end do
         call check(error, maxval(abs(tke_int)) == 0.0_wp, &
                    "scatter: tke_int must be zeroed in vertex mode")
         if (allocated(error)) exit checks

         ! ---- Geometric mode, kdmin = 0 ----
         call kappa_shear_vertex_scatter(NXL, NYL, NZP1, .true., 0.0_wp, &
                                         wet_t, kd_corner, kd_int, tke_int)
         gm = sqrt(sqrt((A*D)*(C*B)))
         call check(error, abs(kd_int(2, 2, 2) - gm) <= TOL, &
                    "scatter geometric: 4th root of the corner product")
         if (allocated(error)) exit checks
         call check(error, gm <= am, "AM-GM: geometric <= arithmetic")
         if (allocated(error)) exit checks

         ! One corner exactly 0 with kdmin = 0 -> hard 0.
         kd_corner(2, 2, 2) = 0.0_wp
         call kappa_shear_vertex_scatter(NXL, NYL, NZP1, .true., 0.0_wp, &
                                         wet_t, kd_corner, kd_int, tke_int)
         call check(error, kd_int(2, 2, 2) == 0.0_wp, &
                    "scatter geometric kdmin=0: one zero corner zeros the cell")
         if (allocated(error)) exit checks

         ! Same with kdmin = 1e-9 -> the floored 4th root.
         call kappa_shear_vertex_scatter(NXL, NYL, NZP1, .true., KDMIN, &
                                         wet_t, kd_corner, kd_int, tke_int)
         expect = sqrt(sqrt((KDMIN*D)*(C*B)))
         call check(error, abs(kd_int(2, 2, 2) - expect) <= TOL, &
                    "scatter geometric kdmin=1e-9: floored corner enters the product")
      end block checks
   end subroutine test_vertex_scatter_modes

   ! ------------------------------------------------------------------
   ! Test 10: vertex path device residency (mem:separate)
   ! ------------------------------------------------------------------

   subroutine test_vertex_device_resident(error)
      !! Run the vertex path twice: once with nothing mapped (the
      !! reference — implicit staging binds the good host copies), then
      !! with the production maps in place and the HOST copies of every
      !! input + the kd_corner carrier POISONED.  Only a run that reads
      !! the mapped DEVICE data can reproduce the reference; a missing
      !! map would implicitly stage the poisoned host copy and diverge.
      !! (Poison is #ifdef RDB_GPU_OFFLOAD — on host builds there is
      !! only one copy and poisoning it would poison the data under
      !! test.)  `update self` pulls the COMPONENT array, never the
      !! aggregate.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 12
      real(wp), parameter :: DZ = 8.0_wp, DT = 1800.0_wp
      real(wp), allocatable :: kd_ref(:, :, :)
      real(wp), allocatable :: wet_t(:, :), wet_u(:, :), wet_v(:, :)
      integer :: i, j, k, nx, ny
      real(wp) :: diff_max
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call setup_ks(ks, grid, NZ)
         call setup_vertex(ks, grid, NZ)
         call setup_shear_column(ms, NZ, DZ, 0.5_wp, 48.0_wp, 20.0_wp, 3.0e-5_wp)
         allocate (wet_t(nx, ny), wet_u(nx + 1, ny), wet_v(nx, ny + 1))
         wet_t = 1.0_wp
         wet_u = 1.0_wp
         wet_v = 1.0_wp

         ! ---- Reference: unmapped run (host data is the good copy) ----
         call kappa_shear_compute(grid, ks, ms, DT, wet_t, wet_u, wet_v)
         allocate (kd_ref(nx, ny, NZ + 1))
         kd_ref = ks%kd_int
         call check(error, maxval(kd_ref) > 0.0_wp, &
                    "vertex device: reference run must produce mixing")
         if (allocated(error)) exit checks

         ! ---- Mapped run with poisoned host inputs ----
         call ms%enter_data()
         call ks%enter_data()
         !$acc enter data copyin(wet_t, wet_u, wet_v)
#ifdef RDB_GPU_OFFLOAD
         call poison_3d(ms%h_layer)
         call poison_3d(ms%u_face_x_layer)
         call poison_3d(ms%v_face_y_layer)
         call poison_3d(ms%tracers(ms%idx_temperature)%hTr)
         call poison_3d(ms%tracers(ms%idx_salinity)%hTr)
         call poison_2d(ks%f_corner)
         call poison_3d(ks%kd_corner)   ! the kernel-1 -> kernel-2 carrier
#endif
         call kappa_shear_compute(grid, ks, ms, DT, wet_t, wet_u, wet_v)
         !$acc update self(ks%kd_int)
         !$acc exit data delete(wet_t, wet_u, wet_v)
         call ks%exit_data()
         call ms%exit_data()

         ! Compare over the FULL array, not just owned cells: the ring
         ! cells (i=1, i=nx, ...) average with the never-written ring
         ! corners of kd_corner, which are 0 on the mapped device copy
         ! but POISON on the host copy — so this window is what makes a
         ! missing kd_corner map detectable (an implicit staging of the
         ! poisoned host array would contaminate exactly these cells).
         diff_max = 0.0_wp
         do k = 1, NZ + 1
            do j = 1, ny
               do i = 1, nx
                  diff_max = max(diff_max, abs(ks%kd_int(i, j, k) - kd_ref(i, j, k)))
               end do
            end do
         end do
         call check(error, diff_max == 0.0_wp, &
                    "vertex device: mapped run must reproduce the reference "// &
                    "bitwise — a mismatch means a kernel read/wrote a stale "// &
                    "or poisoned HOST copy (missing device map)")
      end block checks
      call ks%destroy()
      call ms%destroy()
   end subroutine test_vertex_device_resident

   ! ------------------------------------------------------------------
   ! Tests 11-14: the vertex Kv corner->face seam (PR 2)
   ! MOM6 routes shear VISCOSITY corner->face (Kv_shear_Bu consumed in
   ! vertvisc as the 2-point end-corner average), never via a tracer
   ! point.  These tests must DISCRIMINATE that from the interim
   ! corner->centre->face collapse, which passes every Kd test.
   ! ------------------------------------------------------------------

   subroutine test_vertex_kv_merge_skips_kv(error)
      !! In vertex mode the cell-centred merge must add kd_int to kt
      !! ONLY — the viscosity goes corner->face inside vdiff, and a
      !! centre add here would double-count (MOM6 zeroes the
      !! tracer-point Kv_shear under VERTEX_SHEAR).  Column mode must
      !! keep the historical kv add bit-for-bit.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(ocean_kappa_shear_t) :: ks
      integer, parameter :: NZ = 5
      real(wp), parameter :: KV_BASE = 2.0e-4_wp, KT_BASE = 3.0e-5_wp
      real(wp), parameter :: PR = 0.7_wp
      real(wp), allocatable :: kv(:, :, :), kt(:, :, :)
      integer :: k, nx, ny
      real(wp) :: kd_ref
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         call ks%init(grid, nz_ml=NZ)
         ks%prandtl_turb = PR
         do k = 2, NZ
            ks%kd_int(:, :, k) = real(k, wp)*1.0e-3_wp
         end do

         ! ---- Vertex mode: kv untouched, kt incremented ----
         ks%at_vertex = .true.
         allocate (kv(nx, ny, NZ + 1), source=KV_BASE)
         allocate (kt(nx, ny, NZ + 1), source=KT_BASE)
         call kappa_shear_merge_into_kv_kt(ks, nx, ny, NZ + 1, kv, kt)
         call check(error, maxval(abs(kv - KV_BASE)) == 0.0_wp, &
                    "vertex merge: kv must be BIT-untouched (viscosity goes "// &
                    "corner->face in vdiff; a centre add double-counts)")
         if (allocated(error)) exit checks
         do k = 2, NZ
            kd_ref = real(k, wp)*1.0e-3_wp
            call check(error, abs(kt(1, 1, k) - (KT_BASE + kd_ref)) < 1.0e-15_wp, &
                       "vertex merge: kt must still receive kd_int")
            if (allocated(error)) exit checks
         end do
         if (allocated(error)) exit checks

         ! ---- Column mode contrast: kv gets PR*kd (historical path) ----
         ks%at_vertex = .false.
         kv = KV_BASE
         kt = KT_BASE
         call kappa_shear_merge_into_kv_kt(ks, nx, ny, NZ + 1, kv, kt)
         call check(error, abs(kv(1, 1, 3) - (KV_BASE + PR*3.0e-3_wp)) < 1.0e-15_wp, &
                    "column merge: kv must keep the prandtl_turb*kd add")
      end block checks
      if (allocated(kv)) deallocate (kv, kt)
      call ks%destroy()
   end subroutine test_vertex_kv_merge_skips_kv

   subroutine test_vertex_kv_face_locality(error)
      !! THE staggering discriminator.  A corner viscosity confined to
      !! ONE corner column i = IC0 must, under the direct corner->face
      !! route, touch ONLY:
      !!   u-faces at i = IC0        (end corners (IC0,j)/(IC0,j+1)),
      !!   v-faces at i = IC0-1, IC0 (end corners (i,j)/(i+1,j)).
      !! Every other face column must come out of the implicit solve
      !! BIT-identical to its input (its matrix is exactly the
      !! identity).  The corner->centre->face collapse spreads the
      !! delta to cells IC0-1/IC0 and thence to u-faces IC0-1 and
      !! IC0+1 — asserted explicitly at the end (the collapse run DOES
      !! move u at IC0+1), so a collapsing implementation cannot pass
      !! the untouched-column assertions: the test has teeth.
      !! A transposed corner pair (u reading (i,j)/(i+1,j)) would move
      !! u at IC0-1 — also caught.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 4, IC0 = 6
      real(wp), parameter :: DZ = 10.0_wp, DT = 600.0_wp, KC = 0.02_wp
      real(wp), allocatable :: kv_zero(:, :, :), corner(:, :, :), kv_coll(:, :, :)
      real(wp), allocatable :: u0(:, :, :), v0(:, :, :)
      integer :: i, j, k, nx, ny
      real(wp) :: dmax
      logical :: clean
      checks: block
         call make_grid(grid, 6, 6)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call vd%init(grid, nz_ml=NZ)

         ms%h_layer = DZ
         do k = 1, NZ
            ms%u_face_x_layer(:, :, k) = 0.1_wp*real(k, wp)   ! vertical shear
            ms%v_face_y_layer(:, :, k) = 0.05_wp*real(k*k, wp)
         end do
         allocate (u0, source=ms%u_face_x_layer)
         allocate (v0, source=ms%v_face_y_layer)

         allocate (kv_zero(nx, ny, NZ + 1), source=0.0_wp)
         allocate (corner(nx + 1, ny + 1, NZ + 1), source=0.0_wp)
         corner(IC0, :, 2:NZ) = KC   ! one corner COLUMN, interior interfaces

         ! ---- Run A: direct corner->face route ----
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_zero, &
                                   kv_corner_source=corner, &
                                   kv_corner_prandtl=1.0_wp)

         ! u: column IC0 must move, EVERY other column must be bitwise
         ! untouched.
         call check(error, maxval(abs(ms%u_face_x_layer(IC0, :, :) - u0(IC0, :, :))) > 0.0_wp, &
                    "kv locality: u-faces at the corner column must feel the viscosity")
         if (allocated(error)) exit checks
         clean = .true.
         do k = 1, NZ
            do j = 1, ny
               do i = 1, nx + 1
                  if (i == IC0) cycle
                  if (ms%u_face_x_layer(i, j, k) /= u0(i, j, k)) clean = .false.
               end do
            end do
         end do
         call check(error, clean, &
                    "kv locality: u-faces off the corner column moved — the "// &
                    "viscosity was smoothed through cell centres (or the "// &
                    "corner pair is transposed); MOM6 routes corner->face "// &
                    "with NO tracer-point round trip")
         if (allocated(error)) exit checks

         ! v: columns IC0-1 and IC0 move, every other column bitwise
         ! untouched.
         call check(error, &
                    maxval(abs(ms%v_face_y_layer(IC0 - 1, :, :) - v0(IC0 - 1, :, :))) > 0.0_wp &
                    .and. maxval(abs(ms%v_face_y_layer(IC0, :, :) - v0(IC0, :, :))) > 0.0_wp, &
                    "kv locality: v-faces flanking the corner column must feel it")
         if (allocated(error)) exit checks
         clean = .true.
         do k = 1, NZ
            do j = 1, ny + 1
               do i = 1, nx
                  if (i == IC0 - 1 .or. i == IC0) cycle
                  if (ms%v_face_y_layer(i, j, k) /= v0(i, j, k)) clean = .false.
               end do
            end do
         end do
         call check(error, clean, &
                    "kv locality: v-faces outside the flanking pair moved")
         if (allocated(error)) exit checks

         ! ---- Teeth: the collapse emulation DOES move u at IC0+1 ----
         ! kv_coll is exactly what the corner->centre (Pass-C
         ! arithmetic) collapse would feed the momentum solve; if the
         ! untouched-column assertions above could not tell the two
         ! routes apart, this run would leave IC0+1 untouched too.
         ms%u_face_x_layer = u0
         ms%v_face_y_layer = v0
         allocate (kv_coll(nx, ny, NZ + 1), source=0.0_wp)
         do k = 2, NZ
            do j = 1, ny
               do i = 1, nx
                  kv_coll(i, j, k) = 0.25_wp*((corner(i, j, k) + corner(i + 1, j + 1, k)) + &
                                              (corner(i, j + 1, k) + corner(i + 1, j, k)))
               end do
            end do
         end do
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_coll)
         dmax = maxval(abs(ms%u_face_x_layer(IC0 + 1, :, :) - u0(IC0 + 1, :, :)))
         call check(error, dmax > 0.0_wp, &
                    "kv locality teeth: the centre-collapse emulation must "// &
                    "move u at IC0+1 — otherwise the locality assertions "// &
                    "could not discriminate the two routes")
      end block checks
      if (allocated(kv_zero)) deallocate (kv_zero, corner, u0, v0)
      if (allocated(kv_coll)) deallocate (kv_coll)
      call vd%destroy()
      call ms%destroy()
   end subroutine test_vertex_kv_face_locality

   subroutine test_vertex_kv_corner_vs_centre(error)
      !! Amplitude cross-check, y-varying corner field C = g(jc) with g
      !! NONLINEAR in jc.  Direct corner->face:
      !!   u-face (i,j) gets 0.5*(g(j)+g(j+1))  — the crafted centred
      !!     field kv_ref(j) = 0.5*(g(j)+g(j+1)) reproduces it BITWISE
      !!     (the kernel's own 2-cell average of an x-uniform field is
      !!     0.5*(x+x) = x exactly), so u_A == u_B to the bit;
      !!   v-face (i,j) gets 0.5*(g(j)+g(j)) = g(j) — which NO centred
      !!     field of that construction reproduces (its face average
      !!     re-smooths in j), so v_A /= v_B.
      !! Under the corner->centre->face collapse the centre field IS
      !! kv_ref (the Pass-C arithmetic mean of g(j)/g(j+1) pairs), so
      !! v_A would equal v_B — the v inequality is what discriminates.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 4
      real(wp), parameter :: DZ = 10.0_wp, DT = 600.0_wp
      real(wp), allocatable :: kv_zero(:, :, :), corner(:, :, :), kv_ref(:, :, :)
      real(wp), allocatable :: u0(:, :, :), v0(:, :, :), ua(:, :, :), va(:, :, :)
      integer :: j, k, nx, ny
      real(wp) :: g_lo, g_hi
      checks: block
         call make_grid(grid, 6, 6)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call vd%init(grid, nz_ml=NZ)

         ms%h_layer = DZ
         do k = 1, NZ
            ms%u_face_x_layer(:, :, k) = 0.1_wp*real(k, wp)
            ms%v_face_y_layer(:, :, k) = 0.05_wp*real(k*k, wp)
         end do
         allocate (u0, source=ms%u_face_x_layer)
         allocate (v0, source=ms%v_face_y_layer)

         allocate (kv_zero(nx, ny, NZ + 1), source=0.0_wp)
         allocate (corner(nx + 1, ny + 1, NZ + 1), source=0.0_wp)
         allocate (kv_ref(nx, ny, NZ + 1), source=0.0_wp)
         do k = 2, NZ
            do j = 1, ny + 1
               corner(:, j, k) = g_of(j)          ! y-only, nonlinear in j
            end do
            do j = 1, ny
               g_lo = g_of(j)
               g_hi = g_of(j + 1)
               ! EXACTLY the kernel's corner term for a u-face at row j
               ! (prandtl = 1): 1.0*(0.5*(c1 + c2)).
               kv_ref(:, j, k) = 1.0_wp*(0.5_wp*(g_lo + g_hi))
            end do
         end do

         ! ---- Run A: corner route ----
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_zero, &
                                   kv_corner_source=corner, &
                                   kv_corner_prandtl=1.0_wp)
         allocate (ua, source=ms%u_face_x_layer)
         allocate (va, source=ms%v_face_y_layer)
         call check(error, maxval(abs(ua - u0)) > 0.0_wp, &
                    "kv corner-vs-centre: run A must actually mix u")
         if (allocated(error)) exit checks

         ! ---- Run B: the equivalent centred field ----
         ms%u_face_x_layer = u0
         ms%v_face_y_layer = v0
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_ref)

         call check(error, maxval(abs(ua - ms%u_face_x_layer)) == 0.0_wp, &
                    "kv corner-vs-centre: u must match the crafted centred "// &
                    "field BITWISE (the u-face 2-corner average of a y-only "// &
                    "field equals the 2-cell average of its pair means exactly)")
         if (allocated(error)) exit checks
         call check(error, maxval(abs(va - ms%v_face_y_layer)) > 0.0_wp, &
                    "kv corner-vs-centre: v must DIFFER from the centred "// &
                    "route — direct corner->face gives the un-smoothed g(j) "// &
                    "at v-faces; equality here means the implementation "// &
                    "collapsed the corner field to cell centres")
      end block checks
      if (allocated(kv_zero)) deallocate (kv_zero, corner, kv_ref, u0, v0)
      if (allocated(ua)) deallocate (ua, va)
      call vd%destroy()
      call ms%destroy()
   end subroutine test_vertex_kv_corner_vs_centre

   pure function g_of(jc) result(g)
      !! Nonlinear corner-row viscosity profile for the corner-vs-centre
      !! test (nonlinearity is what makes the v-face smoothing visible).
      integer, intent(in) :: jc
      real(wp) :: g
      g = 1.0e-3_wp*real(jc*jc, wp)
   end function g_of

   subroutine test_vertex_kv_device_resident(error)
      !! Device residency of the corner Kv seam (mem:separate).  For
      !! explicit-shape `do concurrent` dummies nvfortran emits an
      !! implicit copyin for an UNMAPPED array — so it silently stages
      !! the HOST copy and a plain map-and-compare passes vacuously.
      !! Construction: unmapped reference run first (implicit staging
      !! binds the good host copies), then a mapped run with the host
      !! copies POISONED — only a kernel reading the mapped DEVICE
      !! copies can reproduce the reference bitwise.
      type(error_type), allocatable, intent(out) :: error
      type(hgrid_t) :: grid
      type(multilayer_state_t) :: ms
      type(ocean_vdiff_t) :: vd
      integer, parameter :: NZ = 6
      real(wp), parameter :: DZ = 10.0_wp, DT = 600.0_wp
      real(wp), allocatable :: kv_zero(:, :, :), corner(:, :, :)
      real(wp), allocatable :: u0(:, :, :), v0(:, :, :), u_ref(:, :, :), v_ref(:, :, :)
      integer :: jc, k, nx, ny
      real(wp) :: dmax
      checks: block
         call make_grid(grid, 4, 4)
         nx = grid%nx_total
         ny = grid%ny_total
         ms%nz_ml = NZ
         call ms%init(grid)
         call vd%init(grid, nz_ml=NZ)

         ms%h_layer = DZ
         do k = 1, NZ
            ms%u_face_x_layer(:, :, k) = 0.1_wp*real(k, wp)
            ms%v_face_y_layer(:, :, k) = 0.05_wp*real(k*k, wp)
         end do
         allocate (u0, source=ms%u_face_x_layer)
         allocate (v0, source=ms%v_face_y_layer)
         allocate (kv_zero(nx, ny, NZ + 1), source=0.0_wp)
         allocate (corner(nx + 1, ny + 1, NZ + 1), source=0.0_wp)
         do k = 2, NZ
            do jc = 1, ny + 1
               corner(:, jc, k) = 1.0e-3_wp*real(jc + k, wp)
            end do
         end do

         ! ---- Reference: unmapped run (host data is the good copy) ----
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_zero, &
                                   kv_corner_source=corner, &
                                   kv_corner_prandtl=1.0_wp)
         allocate (u_ref, source=ms%u_face_x_layer)
         allocate (v_ref, source=ms%v_face_y_layer)
         call check(error, maxval(abs(u_ref - u0)) > 0.0_wp, &
                    "kv device: reference run must actually mix u")
         if (allocated(error)) exit checks

         ! ---- Mapped run with poisoned host inputs ----
         ms%u_face_x_layer = u0
         ms%v_face_y_layer = v0
         !$acc enter data copyin(ms)
         call ms%enter_data()
         !$acc enter data copyin(vd)
         call vd%enter_data()
         !$acc enter data copyin(kv_zero, corner)
#ifdef RDB_GPU_OFFLOAD
         call poison_3d(ms%h_layer)
         call poison_3d(kv_zero)
         call poison_3d(corner)   ! the corner Kv source under test
#endif
         call vdiff_apply_momentum(grid, vd, ms, DT, kv_source=kv_zero, &
                                   kv_corner_source=corner, &
                                   kv_corner_prandtl=1.0_wp)
         !$acc update self(ms%u_face_x_layer, ms%v_face_y_layer)
         !$acc exit data delete(kv_zero, corner)
         call vd%exit_data()
         !$acc exit data delete(vd)
         call ms%exit_data()
         !$acc exit data delete(ms)

         dmax = max(maxval(abs(ms%u_face_x_layer - u_ref)), &
                    maxval(abs(ms%v_face_y_layer - v_ref)))
         call check(error, dmax == 0.0_wp, &
                    "kv device: mapped run must reproduce the reference "// &
                    "bitwise — a mismatch means the kernel staged a "// &
                    "poisoned HOST copy (missing device map on the corner "// &
                    "Kv source)")
      end block checks
      if (allocated(kv_zero)) deallocate (kv_zero, corner, u0, v0)
      if (allocated(u_ref)) deallocate (u_ref, v_ref)
      call vd%destroy()
      call ms%destroy()
   end subroutine test_vertex_kv_device_resident

   subroutine poison_3d(buf)
      !! Overwrite the HOST copy of an already-mapped 3-D buffer with a
      !! value far outside the physical range.  Plain sequential loops —
      !! never `do concurrent` and never array syntax — so the store
      !! cannot be offloaded (which would poison the copy under test).
      ! assumed-shape-ok: host-only helper, no `do concurrent` here.
      real(wp), intent(inout) :: buf(:, :, :)
      integer :: i, j, k
      do k = 1, size(buf, 3)
         do j = 1, size(buf, 2)
            do i = 1, size(buf, 1)
               buf(i, j, k) = -9.999e30_wp
            end do
         end do
      end do
   end subroutine poison_3d

   subroutine poison_2d(buf)
      !! 2-D twin of `poison_3d` (same host-only sequential-store rule).
      ! assumed-shape-ok: host-only helper, no `do concurrent` here.
      real(wp), intent(inout) :: buf(:, :)
      integer :: i, j
      do j = 1, size(buf, 2)
         do i = 1, size(buf, 1)
            buf(i, j) = -9.999e30_wp
         end do
      end do
   end subroutine poison_2d

end module test_ocean_kappa_shear
