"""GENERATED by tests/regression/vcoord_matrix_pin.py -- DO NOT EDIT.

The MEASURED vertical-coordinate matrix: per-family viscous-leg rx0
ENVELOPES and one record per failing cell (union of failing
assertions over toolchains and tiers, every toolchain's number
quoted).  Re-measure and regenerate; never hand-edit a number.

Provenance: tier 1 = 30 simulated days, tier 2 = 3.33 days; gfortran 15.1.0 Release (CPU) and nvfortran 26.5 (GPU, cc70, one V100); RDB_ENABLE_MPI=OFF, single rank; origin/main 6cf0e317e + this branch; 2026-09-22
"""

ENVELOPES = {
    'eulerian_z': 0.6,
    'hycom': 0.0,
    'lagrangian': 0.03,
    'rho': 0.0,
    'sigma': 0.078,
    'z_fixed': 0.0,
    'zstar': 0.078,
    'zstar_full': 0.1,
    'zstar_sigma': 0.1,
}

# Base cells (the default pred_corr).
MEASURED = {
    'inviscid': {
        'lid_slope/z_fixed': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0007684',
                'nvfortran': 'tier 1: peak En 0.0007684',
            },
        },
        'rx0_010/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.000799, En e-folding 0.65 d',
                'nvfortran': 'tier 1: peak En 0.0007713, En e-folding 0.64 d',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0 on the remap guard (h -626.7 m)',
                'nvfortran': 'tier 1: aborts day 6.0 on the remap guard (h -0.0002015 m)',
            },
        },
        'rx0_010/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 12.0 non-finite',
                'nvfortran': 'tier 1: aborts day 10.5 non-finite',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 3.0 on the remap guard (h -0.0002749 m)',
                'nvfortran': 'tier 1: aborts day 2.5 on the remap guard (h NaN m)',
            },
        },
        'rx0_010/sigma': {
            "assertions": ['energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.678e-12, En e-folding 0.86 d',
                'nvfortran': 'tier 1: peak En 2.293e-12, En e-folding 0.86 d',
            },
        },
        'rx0_010/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.198e-07, En e-folding 3.22 d, salt residual 1.342e-07',
                'nvfortran': 'tier 1: peak En 1.198e-07, En e-folding 3.22 d, salt residual 1.342e-07',
            },
        },
        'rx0_010/zstar': {
            "assertions": ['energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.678e-12, En e-folding 0.86 d',
                'nvfortran': 'tier 1: peak En 2.293e-12, En e-folding 0.86 d',
            },
        },
        'rx0_020/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 21.5 non-finite',
                'nvfortran': 'tier 1: aborts day 22.0 non-finite',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 1.0 on the remap guard (h -9.362e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.5 on the remap guard (h -1.309e-05 m)',
            },
        },
        'rx0_020/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.0 non-finite',
                'nvfortran': 'tier 1: aborts day 7.0 non-finite',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 1.0 on the remap guard (h -0.0001074 m)',
                'nvfortran': 'tier 1: aborts day 1.0 on the remap guard (h -9.037e-05 m)',
            },
        },
        'rx0_020/sigma': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0007011, En e-folding 0.56 d',
                'nvfortran': 'tier 1: peak En 0.0007365, En e-folding 0.56 d',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 3.128e-07, salt residual 3.349e-07',
                'nvfortran': 'tier 1: peak En 3.128e-07, salt residual 3.349e-07',
            },
        },
        'rx0_020/zstar': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0007011, En e-folding 0.56 d',
                'nvfortran': 'tier 1: peak En 0.0007365, En e-folding 0.56 d',
            },
        },
        'rx0_020/zstar_full': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.372e-05, En e-folding 0.56 d',
                'nvfortran': 'tier 1: peak En 6.58e-05, En e-folding 0.56 d',
            },
        },
        'rx0_020/zstar_sigma': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0006978, En e-folding 0.56 d',
                'nvfortran': 'tier 1: peak En 0.0007261, En e-folding 0.56 d',
            },
        },
        'rx0_040/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 11.0 non-finite',
                'nvfortran': 'tier 1: aborts day 11.0 non-finite',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.1342 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -4.093 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.0 non-finite',
                'nvfortran': 'tier 1: aborts day 5.0 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.129 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -2.798 m)',
            },
        },
        'rx0_040/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 29.5 on the remap guard (h -242.1 m)',
                'nvfortran': 'tier 1: aborts day 29.0 on the remap guard (h -1117 m)',
            },
        },
        'rx0_040/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.295e-08, salt residual 5.335e-07',
                'nvfortran': 'tier 1: peak En 2.295e-08, salt residual 5.335e-07',
            },
        },
        'rx0_040/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 29.5 on the remap guard (h -242.1 m)',
                'nvfortran': 'tier 1: aborts day 29.0 on the remap guard (h -1117 m)',
            },
        },
        'rx0_040/zstar_full': {
            "assertions": ['cfl:no-runaway', 'energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0004193, En e-folding 0.57 d',
                'nvfortran': 'tier 1: peak En 0.0004679, En e-folding 0.57 d',
            },
        },
        'rx0_040/zstar_sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 28.0 on the remap guard (h -195.3 m)',
                'nvfortran': 'tier 1: aborts day 29.5 on the remap guard (h -53.92 m)',
            },
        },
        'rx0_060/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.5 non-finite; tier 2: passes',
                'nvfortran': 'tier 1: aborts day 6.5 non-finite; tier 2: passes',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.5 on the remap guard (h -0.1423 m); tier 2: aborts day 0.4 on the remap guard (h -0.1423 m)',
                'nvfortran': 'tier 1: aborts day 0.5 on the remap guard (h -5.238e-05 m); tier 2: aborts day 0.6 on the remap guard (h NaN m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'energy:rest', 'energy:rest-settles', 'finite'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0 non-finite; tier 2: peak En 8.289e-07',
                'nvfortran': 'tier 1: aborts day 4.0 non-finite; tier 2: peak En 5.334e-07',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -79.43 m); tier 2: aborts day 0.2 on the remap guard (h -79.43 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002034 m); tier 2: aborts day 0.4 on the remap guard (h -0.002034 m)',
            },
        },
        'rx0_060/sigma': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.225e-05, En e-folding 0.63 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 2.537e-05, En e-folding 0.63 d; tier 2: passes',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.654e-07, salt residual 7.3e-07; tier 2: peak En 1.424e-07, salt residual 7.3e-07',
                'nvfortran': 'tier 1: peak En 2.654e-07, salt residual 7.3e-07; tier 2: peak En 1.424e-07, salt residual 7.3e-07',
            },
        },
        'rx0_060/zstar': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.225e-05, En e-folding 0.63 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 2.537e-05, En e-folding 0.63 d; tier 2: passes',
            },
        },
        'rx0_060/zstar_full': {
            "assertions": ['energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.701e-09, En e-folding 0.80 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 4.397e-10, En e-folding 0.86 d; tier 2: passes',
            },
        },
        'rx0_060/zstar_sigma': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.469e-05, En e-folding 0.63 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 1.75e-05, En e-folding 0.63 d; tier 2: passes',
            },
        },
        'rx0_080/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.5 non-finite',
                'nvfortran': 'tier 1: aborts day 4.0 non-finite',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -11.35 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -135.8 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.5 non-finite',
                'nvfortran': 'tier 1: aborts day 4.0 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -4.682 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -67.04 m)',
            },
        },
        'rx0_080/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 on the remap guard (h -52.7 m)',
                'nvfortran': 'tier 1: aborts day 13.5 on the remap guard (h -19.71 m)',
            },
        },
        'rx0_080/sigma/unstrat': {
            "assertions": ['completed', 'finite', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 20.0 non-finite',
                'nvfortran': 'tier 1: aborts day 1.0 on the remap guard (h -159.1 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.295e-07, salt residual 8.578e-07',
                'nvfortran': 'tier 1: peak En 2.295e-07, salt residual 8.578e-07',
            },
        },
        'rx0_080/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 on the remap guard (h -52.7 m)',
                'nvfortran': 'tier 1: aborts day 13.5 on the remap guard (h -19.71 m)',
            },
        },
        'rx0_080/zstar_full': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 3.5 on the remap guard (h -153.9 m)',
                'nvfortran': 'tier 1: aborts day 3.5 on the remap guard (h -26.9 m)',
            },
        },
        'rx0_080/zstar_sigma': {
            "assertions": ['completed', 'finite', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 non-finite',
                'nvfortran': 'tier 1: aborts day 13.5 on the remap guard (h -210.3 m)',
            },
        },
        'seamount_gentle/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0002052, En e-folding 0.53 d',
                'nvfortran': 'tier 1: peak En 0.00018, En e-folding 0.50 d',
            },
        },
        'seamount_gentle/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.5 on the remap guard (h -27.82 m)',
                'nvfortran': 'tier 1: aborts day 16.0 on the remap guard (h -10.08 m)',
            },
        },
        'seamount_gentle/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 11.0 on the remap guard (h -41.6 m)',
                'nvfortran': 'tier 1: aborts day 11.0 on the remap guard (h -0.06733 m)',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest-growth-rate', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.37e-05, En e-folding 13.01 d, salt residual 1.225e-06',
                'nvfortran': 'tier 1: peak En 1.37e-05, En e-folding 13.01 d, salt residual 1.225e-06',
            },
        },
        'seamount_steep/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 20.5 non-finite',
                'nvfortran': 'tier 1: aborts day 15.5 non-finite',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.0 on the remap guard (h -3.472e-05 m)',
                'nvfortran': 'tier 1: aborts day 5.5 on the remap guard (h -2.426 m)',
            },
        },
        'seamount_steep/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0',
                'nvfortran': 'tier 1: aborts day 4.5 non-finite',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.5 on the remap guard (h -187.9 m)',
                'nvfortran': 'tier 1: aborts day 6.0 on the remap guard (h -1.08e-05 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0001418, salt residual 3.017e-07',
                'nvfortran': 'tier 1: peak En 0.0001418, salt residual 3.017e-07',
            },
        },
        'slope/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.001165; tier 2: passes',
                'nvfortran': 'tier 1: peak En 0.001151; tier 2: passes',
            },
        },
        'slope/hycom': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.386e-06, En e-folding 0.82 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 7.733e-07, En e-folding 0.87 d; tier 2: passes',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1, 2],
            "toolchain_dependent": True,
            "measured": {
                'gfortran': 'tier 1: peak En 2.233e-06, En e-folding 1.08 d; tier 2: passes',
                'nvfortran': 'tier 1: aborts; tier 2: aborts',
            },
        },
        'slope/rho': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.297e-06, En e-folding 0.75 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 6.802e-07, En e-folding 0.90 d; tier 2: passes',
            },
        },
        'slope/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.643e-07, salt residual 4.386e-07; tier 2: peak En 6.095e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 1: peak En 5.643e-07, salt residual 4.386e-07; tier 2: peak En 6.095e-07, salt residual 4.386e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.658e-07, salt residual 4.386e-07; tier 2: peak En 6.111e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 1: peak En 5.658e-07, salt residual 4.386e-07; tier 2: peak En 6.111e-07, salt residual 4.386e-07',
            },
        },
    },
    'viscous': {
        'lid_slope/z_fixed': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 6.633e-05',
                'nvfortran': 'tier 1: peak En 6.633e-05',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.06797 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.2377 m)',
            },
        },
        'rx0_010/lagrangian': {
            "assertions": ['energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.655e-09, En e-folding 0.74 d',
                'nvfortran': 'tier 1: peak En 8.302e-09, En e-folding 0.74 d',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3005 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.2463 m)',
            },
        },
        'rx0_010/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 on the remap guard (h -254.8 m)',
                'nvfortran': 'tier 1: aborts day 19.0 on the remap guard (h -115.1 m)',
            },
        },
        'rx0_010/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 6.429e-12, salt residual 1.342e-07',
                'nvfortran': 'tier 1: peak En 6.429e-12, salt residual 1.342e-07',
            },
        },
        'rx0_010/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 on the remap guard (h -254.8 m)',
                'nvfortran': 'tier 1: aborts day 19.0 on the remap guard (h -115.1 m)',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0001127 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.9349 m)',
            },
        },
        'rx0_020/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.5 non-finite',
                'nvfortran': 'tier 1: aborts day 14.5 non-finite',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -5.41e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -77.72 m)',
            },
        },
        'rx0_020/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.0 on the remap guard (h -5.882 m)',
                'nvfortran': 'tier 1: aborts day 3.5 on the remap guard (h -67.13 m)',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.518e-08, salt residual 3.349e-07',
                'nvfortran': 'tier 1: peak En 1.518e-08, salt residual 3.349e-07',
            },
        },
        'rx0_020/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.0 on the remap guard (h -5.882 m)',
                'nvfortran': 'tier 1: aborts day 3.5 on the remap guard (h -67.13 m)',
            },
        },
        'rx0_020/zstar_full': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 2.5 on the remap guard (h -20.25 m)',
                'nvfortran': 'tier 1: aborts day 2.5 on the remap guard (h -1.386e+04 m)',
            },
        },
        'rx0_020/zstar_sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.0 on the remap guard (h -153.4 m)',
                'nvfortran': 'tier 1: aborts day 5.5 on the remap guard (h -2.462 m)',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.000124 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0008236 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 8.5 non-finite',
                'nvfortran': 'tier 1: aborts day 8.5 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0002749 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0008599 m)',
            },
        },
        'rx0_040/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 2.0 on the remap guard (h -427.4 m)',
                'nvfortran': 'tier 1: aborts day 1.5 on the remap guard (h -0.4468 m)',
            },
        },
        'rx0_040/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.681e-10, salt residual 5.335e-07',
                'nvfortran': 'tier 1: peak En 2.681e-10, salt residual 5.335e-07',
            },
        },
        'rx0_040/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 2.0 on the remap guard (h -427.4 m)',
                'nvfortran': 'tier 1: aborts day 1.5 on the remap guard (h NaN m)',
            },
        },
        'rx0_040/zstar_full': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 1.0 on the remap guard (h -161 m)',
                'nvfortran': 'tier 1: aborts day 1.0 on the remap guard (h -31.48 m)',
            },
        },
        'rx0_040/zstar_sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 2.5 on the remap guard (h -25.13 m)',
                'nvfortran': 'tier 1: aborts day 6.5 on the remap guard (h -398.9 m)',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001994 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0006033 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.0 non-finite',
                'nvfortran': 'tier 1: aborts day 6.5 non-finite',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.01105 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.004902 m)',
            },
        },
        'rx0_060/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 15.0 on the remap guard (h -1.384 m)',
                'nvfortran': 'tier 1: aborts day 24.0 on the remap guard (h -65.8 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.385e-08, salt residual 7.3e-07',
                'nvfortran': 'tier 1: peak En 1.385e-08, salt residual 7.3e-07',
            },
        },
        'rx0_060/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 15.0 on the remap guard (h -1.384 m)',
                'nvfortran': 'tier 1: aborts day 24.0 on the remap guard (h -65.8 m)',
            },
        },
        'rx0_060/zstar_full': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 16.5 on the remap guard (h -7.965 m)',
                'nvfortran': 'tier 1: aborts day 15.5 on the remap guard (h -5.042e-05 m)',
            },
        },
        'rx0_080/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0001698, En e-folding 1.25 d',
                'nvfortran': 'tier 1: peak En 0.000141, En e-folding 0.65 d',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005227 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005431 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.5 non-finite',
                'nvfortran': 'tier 1: aborts day 7.0 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0126 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.01301 m)',
            },
        },
        'rx0_080/sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 21.0 on the remap guard (h -0.06878 m)',
                'nvfortran': 'tier 1: aborts day 28.0 on the remap guard (h -2.077e+12 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 7.483e-09, salt residual 8.578e-07',
                'nvfortran': 'tier 1: peak En 7.483e-09, salt residual 8.578e-07',
            },
        },
        'rx0_080/zstar': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 21.0 on the remap guard (h -0.06878 m)',
                'nvfortran': 'tier 1: aborts day 28.0 on the remap guard (h -2.077e+12 m)',
            },
        },
        'rx0_080/zstar_sigma': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 14.0 on the remap guard (h -2.85 m)',
                'nvfortran': 'tier 1: aborts day 23.5 on the remap guard (h -10.43 m)',
            },
        },
        'seamount_gentle/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.007839 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.006947 m)',
            },
        },
        'seamount_gentle/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.006286 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.007812 m)',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.295e-07, salt residual 1.225e-06',
                'nvfortran': 'tier 1: peak En 1.295e-07, salt residual 1.225e-06',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.1006 m); tier 2: aborts day 0.0 on the remap guard (h -0.1006 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.04033 m); tier 2: aborts day 0.0 on the remap guard (h -0.04033 m)',
            },
        },
        'seamount_steep/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 15.5 non-finite; tier 2: passes',
                'nvfortran': 'tier 1: aborts day 15.0 non-finite; tier 2: passes',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.08773 m); tier 2: aborts day 0.0 on the remap guard (h -0.08773 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.04755 m); tier 2: aborts day 0.0 on the remap guard (h -0.04755 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['completed', 'conserve:Heat', 'conserve:Salt', 'remap:preconditions', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 18.5 on the remap guard (h -0.3664 m); tier 2: peak En 1.187e-07, salt residual 3.017e-07',
                'nvfortran': 'tier 1: aborts day 18.5 on the remap guard (h -0.3663 m); tier 2: peak En 1.187e-07, salt residual 3.017e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0005016 m); tier 2: aborts day 0.0 on the remap guard (h -0.0005016 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001585 m); tier 2: aborts day 0.0 on the remap guard (h -0.001585 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.03477 m); tier 2: aborts day 0.0 on the remap guard (h -0.03477 m)',
                'nvfortran': 'tier 1: aborts; tier 2: aborts',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001495 m); tier 2: aborts day 0.0 on the remap guard (h -0.001495 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001687 m); tier 2: aborts day 0.0 on the remap guard (h -0.001687 m)',
            },
        },
        'slope/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.727e-08, salt residual 4.386e-07; tier 2: peak En 1.355e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 1: peak En 4.727e-08, salt residual 4.386e-07; tier 2: peak En 1.355e-07, salt residual 4.386e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.741e-08, salt residual 4.386e-07; tier 2: peak En 1.358e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 1: peak En 4.741e-08, salt residual 4.386e-07; tier 2: peak En 1.358e-07, salt residual 4.386e-07',
            },
        },
    },
}

# The `__ssp_rk2` twins (tier 2 only), pinned separately so a
# twin-only failure does not loosen the base cell's marker.
MEASURED_TWIN = {
    'inviscid': {
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.2 on the remap guard (h -0.04312 m)',
                'nvfortran': 'tier 2: aborts day 0.2 on the remap guard (h -0.04334 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['energy:rest-settles'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.594e-08',
                'nvfortran': 'tier 2: peak En 3.317e-10',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.2 on the remap guard (h -2.912 m)',
                'nvfortran': 'tier 2: aborts day 0.2 on the remap guard (h -0.5796 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 6.52e-06, salt residual 7.3e-07',
                'nvfortran': 'tier 2: peak En 6.52e-06, salt residual 7.3e-07',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed'],
            "tiers": [2],
            "toolchain_dependent": True,
            "measured": {
                'gfortran': 'tier 2: passes',
                'nvfortran': 'tier 2: aborts',
            },
        },
        'slope/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 6.2e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 2: peak En 6.2e-07, salt residual 4.386e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 6.216e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 2: peak En 6.216e-07, salt residual 4.386e-07',
            },
        },
    },
    'viscous': {
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -9.504e-05 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.003403 m)',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -9.53e-05 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.003398 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.192e-07, salt residual 3.017e-07',
                'nvfortran': 'tier 2: peak En 1.192e-07, salt residual 3.017e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -2.431 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -1.565 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -2.878 m)',
                'nvfortran': 'tier 2: aborts',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -1.036 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -2.419 m)',
            },
        },
        'slope/z_fixed': {
            "assertions": ['conserve:Heat', 'conserve:Salt'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.368e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 2: peak En 1.368e-07, salt residual 4.386e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['conserve:Heat', 'conserve:Salt'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.372e-07, salt residual 4.386e-07',
                'nvfortran': 'tier 2: peak En 1.372e-07, salt residual 4.386e-07',
            },
        },
    },
}
