"""GENERATED by tests/regression/vcoord_matrix_pin.py -- DO NOT EDIT.

The MEASURED vertical-coordinate matrix: per-family viscous-leg rx0
ENVELOPES and one record per failing cell (union of failing
assertions over toolchains and tiers, every toolchain's number
quoted).  Re-measure and regenerate; never hand-edit a number.

Provenance: tier 1 = 30 simulated days (10 for the seamount and rx0 problems, T1_STEPS_SEAMOUNT), tier 2 = 3.33 days; gfortran 15.1.0 Release -march=x86-64-v3 (CPU) and nvfortran 26.5 (GPU, cc70, V100); RDB_ENABLE_MPI=OFF, single rank; the MOM6 barotropic split (bc_pgf_forcing) + FV_MOM6 in-situ density + the lid_slope rows trimmed to the ice load (trim_ic_for_p_surf) + z_fixed lid rows on the layer-mean PCM density; fix/bt-drake-transport-gap 8045ac176 (main a50a4cc82); 2026-09-25
"""

ENVELOPES = {
    'eulerian_z': 0.8,
    'hycom': 0.0,
    'lagrangian': 0.2,
    'rho': 0.0,
    'sigma': 0.8,
    'z_fixed': 0.0,
    'zstar': 0.8,
    'zstar_full': 0.8,
    'zstar_sigma': 0.8,
}

# Base cells (the default pred_corr).
MEASURED = {
    'inviscid': {
        'lid_slope/sigma/unstrat': {
            "assertions": ['energy:rest'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 9.997e-13',
                'nvfortran': 'tier 1: peak En 9.997e-13',
            },
        },
        'lid_slope/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.113e-06',
                'nvfortran': 'tier 1: peak En 1.113e-06',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.3 on the remap guard (h -1.735e-05 m)',
                'nvfortran': 'tier 1: aborts day 9.7 on the remap guard (h -9.723e-06 m)',
            },
        },
        'rx0_010/lagrangian': {
            "assertions": ['energy:rest'],
            "tiers": [1],
            "toolchain_dependent": True,
            "measured": {
                'gfortran': 'tier 1: peak En 7.244e-07',
                'nvfortran': 'tier 1: passes',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 3.5 on the remap guard (h -6.324e-07 m)',
                'nvfortran': 'tier 1: aborts day 3.3 on the remap guard (h -1.51e-06 m)',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.7 on the remap guard (h -9.11e-07 m)',
                'nvfortran': 'tier 1: aborts day 0.8 on the remap guard (h -1.958e-05 m)',
            },
        },
        'rx0_020/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.8 non-finite',
                'nvfortran': 'tier 1: aborts day 7.7 non-finite',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.8 on the remap guard (h -1.284e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.7 on the remap guard (h -0.0002174 m)',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.698e-07',
                'nvfortran': 'tier 1: peak En 2.698e-07',
            },
        },
        'rx0_040/eulerian_z': {
            "assertions": ['cfl:no-runaway', 'energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.002325',
                'nvfortran': 'tier 1: peak En 0.002852',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.424e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.2 on the remap guard (h -3.912e-05 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.5 non-finite',
                'nvfortran': 'tier 1: aborts day 4.3 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.553e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -9.161e-06 m)',
            },
        },
        'rx0_060/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.3 non-finite; tier 2: passes',
                'nvfortran': 'tier 1: aborts day 6.2 non-finite; tier 2: passes',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -3.125e-05 m); tier 2: aborts day 0.0 on the remap guard (h -3.125e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.921e-05 m); tier 2: aborts day 0.0 on the remap guard (h -1.921e-05 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'energy:rest', 'energy:rest-settles', 'finite'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 3.8 non-finite; tier 2: peak En 7.135e-07',
                'nvfortran': 'tier 1: aborts day 3.7 non-finite; tier 2: peak En 3.581e-06',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0004028 m); tier 2: aborts day 0.0 on the remap guard (h -0.0004028 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -9.171e-05 m); tier 2: aborts day 0.0 on the remap guard (h -9.171e-05 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.906e-07; tier 2: peak En 1.248e-07',
                'nvfortran': 'tier 1: peak En 1.906e-07; tier 2: peak En 1.248e-07',
            },
        },
        'rx0_080/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0 non-finite',
                'nvfortran': 'tier 1: aborts day 4.0 non-finite',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.01653 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.883e-07 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.5 non-finite',
                'nvfortran': 'tier 1: aborts day 5.0 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.00194 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001568 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.828e-07',
                'nvfortran': 'tier 1: peak En 1.828e-07',
            },
        },
        'rx0_080/zstar_full': {
            "assertions": ['energy:rest'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.773e-06',
                'nvfortran': 'tier 1: peak En 1.443e-06',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 3.541e-06',
                'nvfortran': 'tier 1: peak En 3.541e-06',
            },
        },
        'seamount_steep/eulerian_z': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0004905',
                'nvfortran': 'tier 1: peak En 0.000447',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.8 on the remap guard (h -0.01388 m)',
                'nvfortran': 'tier 1: aborts day 7.0 on the remap guard (h -0.0001018 m)',
            },
        },
        'seamount_steep/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.2 non-finite',
                'nvfortran': 'tier 1: aborts day 4.2 non-finite',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.0 on the remap guard (h -1.681e-06 m)',
                'nvfortran': 'tier 1: aborts day 6.7 on the remap guard (h -2.218e-05 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 3.62e-05',
                'nvfortran': 'tier 1: peak En 3.62e-05',
            },
        },
        'slope/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.001436; tier 2: passes',
                'nvfortran': 'tier 1: peak En 0.001472; tier 2: passes',
            },
        },
        'slope/hycom': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 8.595e-07, En e-folding 0.82 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 1.996e-06, En e-folding 0.83 d; tier 2: passes',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.284e-06, En e-folding 0.88 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 1.47e-06, En e-folding 0.79 d; tier 2: passes',
            },
        },
        'slope/rho': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.694e-06, En e-folding 0.77 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 2.362e-06, En e-folding 0.82 d; tier 2: passes',
            },
        },
        'slope/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.725e-07; tier 2: peak En 5.19e-07',
                'nvfortran': 'tier 1: peak En 5.725e-07; tier 2: peak En 5.19e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.728e-07; tier 2: peak En 5.202e-07',
                'nvfortran': 'tier 1: peak En 5.728e-07; tier 2: peak En 5.202e-07',
            },
        },
    },
    'viscous': {
        'lid_slope/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.524e-07',
                'nvfortran': 'tier 1: peak En 1.524e-07',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3817 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3485 m)',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3637 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3751 m)',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -5.84e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3968 m)',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3961 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3959 m)',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.829e-08',
                'nvfortran': 'tier 1: peak En 1.829e-08',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001755 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0008625 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.3 non-finite',
                'nvfortran': 'tier 1: aborts day 7.5 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001177 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001101 m)',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0004704 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005831 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.0 non-finite',
                'nvfortran': 'tier 1: aborts day 6.5 non-finite',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001851 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.00434 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.436e-08',
                'nvfortran': 'tier 1: peak En 1.436e-08',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005666 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001933 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.2 non-finite',
                'nvfortran': 'tier 1: aborts day 6.3 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3079 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3079 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.087e-08',
                'nvfortran': 'tier 1: peak En 1.087e-08',
            },
        },
        'seamount_gentle/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.00859 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.007689 m)',
            },
        },
        'seamount_gentle/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005963 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.004959 m)',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.318e-07',
                'nvfortran': 'tier 1: peak En 2.318e-07',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.06225 m); tier 2: aborts day 0.0 on the remap guard (h -0.06225 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.06375 m); tier 2: aborts day 0.0 on the remap guard (h -0.06375 m)',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.08281 m); tier 2: aborts day 0.0 on the remap guard (h -0.08281 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.08394 m); tier 2: aborts day 0.0 on the remap guard (h -0.08394 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.106e-07; tier 2: peak En 1.197e-07',
                'nvfortran': 'tier 1: peak En 1.106e-07; tier 2: peak En 1.197e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002256 m); tier 2: aborts day 0.0 on the remap guard (h -0.002256 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0007623 m); tier 2: aborts day 0.0 on the remap guard (h -0.0007623 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.03659 m); tier 2: aborts day 0.0 on the remap guard (h -0.03659 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.02545 m); tier 2: aborts day 0.0 on the remap guard (h -0.02545 m)',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002446 m); tier 2: aborts day 0.0 on the remap guard (h -0.002446 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001231 m); tier 2: aborts day 0.0 on the remap guard (h -0.001231 m)',
            },
        },
        'slope/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.4e-08; tier 2: passes',
                'nvfortran': 'tier 1: peak En 4.4e-08; tier 2: passes',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.412e-08; tier 2: passes',
                'nvfortran': 'tier 1: peak En 4.412e-08; tier 2: passes',
            },
        },
    },
}

# The `__ssp_rk2` twins (tier 2 only), pinned separately so a
# twin-only failure does not loosen the base cell's marker.
MEASURED_TWIN = {
    'inviscid': {
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.01471 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.1769 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['energy:rest', 'energy:rest-settles'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 9.554e-07',
                'nvfortran': 'tier 2: peak En 2.296e-06',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -1.803 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -9.507 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.02e-05',
                'nvfortran': 'tier 2: peak En 1.019e-05',
            },
        },
        'slope/z_fixed': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 5.3e-07',
                'nvfortran': 'tier 2: peak En 5.3e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 5.312e-07',
                'nvfortran': 'tier 2: peak En 5.312e-07',
            },
        },
    },
    'viscous': {
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -842.5 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.003946 m)',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -842.5 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.004215 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.202e-07',
                'nvfortran': 'tier 2: peak En 1.202e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.166 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.2567 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.007975 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -13.89 m)',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.1766 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.1894 m)',
            },
        },
    },
}
