"""GENERATED by tests/regression/vcoord_matrix_pin.py -- DO NOT EDIT.

The MEASURED vertical-coordinate matrix: per-family viscous-leg rx0
ENVELOPES and one record per failing cell (union of failing
assertions over toolchains and tiers, every toolchain's number
quoted).  Re-measure and regenerate; never hand-edit a number.

Provenance: tier 1 = 30 simulated days (10 for the seamount and rx0 problems, T1_STEPS_SEAMOUNT), tier 2 = 3.33 days; gfortran 15.1.0 Release -march=x86-64-v3 (CPU) and nvfortran 26.5 (GPU, cc70, V100); RDB_ENABLE_MPI=OFF, single rank; main df34a995d (MPI bit-identity round) + the EFP non-finite propagation fix + the barotropic gravity fix (g_bt = GRAVITY under FV_MOM6); fix/lid-unstrat-blip 11c4ba94b; 2026-09-28
"""

ENVELOPES = {
    'eulerian_z': 0.8,
    'hycom': 0.0,
    'lagrangian': 0.2,
    'rho': 0.0,
    'sigma': 0.8,
    'z_fixed': 0.0,
    'zstar': 0.8,
    'zstar_full': 0.8,
    'zstar_sigma': 0.8,
}

# Base cells (the default pred_corr).
MEASURED = {
    'inviscid': {
        'lid_slope/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.113e-06',
                'nvfortran': 'tier 1: peak En 1.113e-06',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 9.2 on the remap guard (h -1.014e-05 m)',
                'nvfortran': 'tier 1: aborts day 3.0 on the remap guard (h -0.0003083 m)',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'energy:rest', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 5.5 on the remap guard (h -1.585e-05 m)',
                'nvfortran': 'tier 1: peak En 0.0003252',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 1.0 on the remap guard (h -4.954e-06 m)',
                'nvfortran': 'tier 1: aborts day 1.0 on the remap guard (h -6.882e-06 m)',
            },
        },
        'rx0_020/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.5 non-finite',
                'nvfortran': 'tier 1: aborts day 6.7 non-finite',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.7 on the remap guard (h -4.237e-06 m)',
                'nvfortran': 'tier 1: aborts day 1.0 on the remap guard (h -0.1279 m)',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.698e-07',
                'nvfortran': 'tier 1: peak En 2.698e-07',
            },
        },
        'rx0_040/eulerian_z': {
            "assertions": ['cfl:no-runaway', 'completed', 'energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 10.0',
                'nvfortran': 'tier 1: peak En 0.002301',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -8.914e-06 m)',
                'nvfortran': 'tier 1: aborts day 0.2 on the remap guard (h -6.806e-05 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.5 non-finite',
                'nvfortran': 'tier 1: aborts day 4.5 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -7.128e-06 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -3.161e-05 m)',
            },
        },
        'rx0_060/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.0 non-finite; tier 2: passes',
                'nvfortran': 'tier 1: aborts day 6.0; tier 2: passes',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -3.271e-05 m); tier 2: aborts day 0.0 on the remap guard (h -3.271e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -1.935e-05 m); tier 2: aborts day 0.0 on the remap guard (h -1.935e-05 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'energy:rest-settles', 'finite'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0 non-finite; tier 2: peak En 1.093e-07',
                'nvfortran': 'tier 1: aborts day 3.8 non-finite; tier 2: peak En 3.891e-07',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0003162 m); tier 2: aborts day 0.0 on the remap guard (h -0.0003162 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -9.175e-05 m); tier 2: aborts day 0.0 on the remap guard (h -9.175e-05 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.906e-07; tier 2: peak En 1.248e-07',
                'nvfortran': 'tier 1: peak En 1.906e-07; tier 2: peak En 1.248e-07',
            },
        },
        'rx0_080/eulerian_z': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.0 non-finite',
                'nvfortran': 'tier 1: aborts day 4.0 non-finite',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0001613 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.04259 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.2 non-finite',
                'nvfortran': 'tier 1: aborts day 4.8 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001978 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001588 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.828e-07',
                'nvfortran': 'tier 1: peak En 1.828e-07',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 3.541e-06',
                'nvfortran': 'tier 1: peak En 3.541e-06',
            },
        },
        'seamount_steep/eulerian_z': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.0002501',
                'nvfortran': 'tier 1: peak En 0.0004711',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.3 on the remap guard (h -1.621e-06 m)',
                'nvfortran': 'tier 1: aborts day 6.2 on the remap guard (h -2.317e-06 m)',
            },
        },
        'seamount_steep/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 4.2 non-finite',
                'nvfortran': 'tier 1: aborts day 4.2 non-finite',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.5 on the remap guard (h -3.35e-05 m)',
                'nvfortran': 'tier 1: aborts day 7.0 on the remap guard (h -2.59 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 3.62e-05',
                'nvfortran': 'tier 1: peak En 3.62e-05',
            },
        },
        'slope/eulerian_z': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 0.001439; tier 2: passes',
                'nvfortran': 'tier 1: peak En 0.001415; tier 2: passes',
            },
        },
        'slope/hycom': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.352e-06, En e-folding 0.76 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 2.039e-06, En e-folding 0.87 d; tier 2: passes',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.985e-06, En e-folding 0.87 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 1.509e-06, En e-folding 0.82 d; tier 2: passes',
            },
        },
        'slope/rho': {
            "assertions": ['energy:rest', 'energy:rest-growth-rate', 'energy:rest-settles'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.097e-06, En e-folding 0.69 d; tier 2: passes',
                'nvfortran': 'tier 1: peak En 9.373e-07, En e-folding 0.85 d; tier 2: passes',
            },
        },
        'slope/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.725e-07; tier 2: peak En 5.19e-07',
                'nvfortran': 'tier 1: peak En 5.725e-07; tier 2: peak En 5.19e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 5.728e-07; tier 2: peak En 5.202e-07',
                'nvfortran': 'tier 1: peak En 5.728e-07; tier 2: peak En 5.202e-07',
            },
        },
    },
    'viscous': {
        'lid_slope/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.524e-07',
                'nvfortran': 'tier 1: peak En 1.524e-07',
            },
        },
        'rx0_010/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3818 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3485 m)',
            },
        },
        'rx0_010/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.364 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.375 m)',
            },
        },
        'rx0_020/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -5.837e-05 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3984 m)',
            },
        },
        'rx0_020/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3961 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3959 m)',
            },
        },
        'rx0_020/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.829e-08',
                'nvfortran': 'tier 1: peak En 1.829e-08',
            },
        },
        'rx0_040/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001527 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0001538 m)',
            },
        },
        'rx0_040/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.7 non-finite',
                'nvfortran': 'tier 1: aborts day 7.3 non-finite',
            },
        },
        'rx0_040/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.00106 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001033 m)',
            },
        },
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0009317 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.006312 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 7.3 non-finite',
                'nvfortran': 'tier 1: aborts day 6.2 non-finite',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002884 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.003654 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.436e-08',
                'nvfortran': 'tier 1: peak En 1.436e-08',
            },
        },
        'rx0_080/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005663 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001931 m)',
            },
        },
        'rx0_080/lagrangian': {
            "assertions": ['completed', 'finite'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 6.0 non-finite',
                'nvfortran': 'tier 1: aborts day 4.8 non-finite',
            },
        },
        'rx0_080/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3079 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.3079 m)',
            },
        },
        'rx0_080/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.087e-08',
                'nvfortran': 'tier 1: peak En 1.087e-08',
            },
        },
        'seamount_gentle/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.007109 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.006696 m)',
            },
        },
        'seamount_gentle/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.005717 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.008503 m)',
            },
        },
        'seamount_gentle/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 2.318e-07',
                'nvfortran': 'tier 1: peak En 2.318e-07',
            },
        },
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.1716 m); tier 2: aborts day 0.0 on the remap guard (h -0.1716 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.157 m); tier 2: aborts day 0.0 on the remap guard (h -0.157 m)',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.1732 m); tier 2: aborts day 0.0 on the remap guard (h -0.1732 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.1629 m); tier 2: aborts day 0.0 on the remap guard (h -0.1629 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 1.106e-07; tier 2: peak En 1.197e-07',
                'nvfortran': 'tier 1: peak En 1.106e-07; tier 2: peak En 1.197e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002256 m); tier 2: aborts day 0.0 on the remap guard (h -0.002256 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.0007628 m); tier 2: aborts day 0.0 on the remap guard (h -0.0007628 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.02647 m); tier 2: aborts day 0.0 on the remap guard (h -0.02647 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.02969 m); tier 2: aborts day 0.0 on the remap guard (h -0.02969 m)',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [1, 2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.002442 m); tier 2: aborts day 0.0 on the remap guard (h -0.002442 m)',
                'nvfortran': 'tier 1: aborts day 0.0 on the remap guard (h -0.001231 m); tier 2: aborts day 0.0 on the remap guard (h -0.001231 m)',
            },
        },
        'slope/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.4e-08; tier 2: passes',
                'nvfortran': 'tier 1: peak En 4.4e-08; tier 2: passes',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [1],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 1: peak En 4.412e-08; tier 2: passes',
                'nvfortran': 'tier 1: peak En 4.412e-08; tier 2: passes',
            },
        },
    },
}

# The `__ssp_rk2` twins (tier 2 only), pinned separately so a
# twin-only failure does not loosen the base cell's marker.
MEASURED_TWIN = {
    'inviscid': {
        'rx0_060/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.002299 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.0753 m)',
            },
        },
        'rx0_060/lagrangian': {
            "assertions": ['energy:rest-settles'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 7.605e-08',
                'nvfortran': 'tier 2: peak En 1.874e-07',
            },
        },
        'rx0_060/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -1.318 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -9.435 m)',
            },
        },
        'rx0_060/z_fixed': {
            "assertions": ['energy:rest', 'energy:rest-settles', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.019e-05',
                'nvfortran': 'tier 2: peak En 1.019e-05',
            },
        },
        'slope/z_fixed': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 5.3e-07',
                'nvfortran': 'tier 2: peak En 5.3e-07',
            },
        },
        'slope/z_fixed/wright': {
            "assertions": ['energy:rest', 'tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 5.312e-07',
                'nvfortran': 'tier 2: peak En 5.312e-07',
            },
        },
    },
    'viscous': {
        'seamount_steep/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -843.2 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.003958 m)',
            },
        },
        'seamount_steep/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -843.1 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.004221 m)',
            },
        },
        'seamount_steep/z_fixed': {
            "assertions": ['tracer:no-new-extrema'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: peak En 1.202e-07',
                'nvfortran': 'tier 2: peak En 1.202e-07',
            },
        },
        'slope/hycom': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.04294 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.1553 m)',
            },
        },
        'slope/hycom/wright': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.2968 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -14.74 m)',
            },
        },
        'slope/rho': {
            "assertions": ['completed', 'remap:preconditions'],
            "tiers": [2],
            "toolchain_dependent": False,
            "measured": {
                'gfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.2844 m)',
                'nvfortran': 'tier 2: aborts day 0.0 on the remap guard (h -0.1716 m)',
            },
        },
    },
}
